xamarin/Essentials

F50.Tests/UnitTest1.cs, F50/F50.csproj, F50/Platform/Platform.android.cs, F50/Platform/Platform.ios.cs, F50/Platform/Platform.netstandard.cs, F50/Platform/Platform.shared.cs, F50/Platform/Platform.uwp.cs, F50/Preferences/Preferences.android.cs, F50/Preferences/Preferences.ios.cs, F50/Preferences/Preferences.netstandard.cs, F50/Preferences/Preferences.shared.cs, F50/Preferences/Preferences.uwp.cs, F50/Preferences/PreferencesExtensions.shared.cs, F50/Shared/F50Exceptions.shared.cs
WIP: Adding preferences implementation
=> Preferences

Caboodle/Preferences/Preferences.shared.cs
Added missing Set methods for Preferences.
=> Added public set methods for preferences

Caboodle/Preferences/Preferences.shared.cs
- use the generic
- Set does not return a value
- make SharedName a readonly value
=> Make sure we don't keep calling the same method recursively

CODE_OF_CONDUCT.md, CONTRIBUTING.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, SUBMITTING-ISSUES.md
Initial attempt at contribution, submission docs, and templates files.
Copied from Xamarin.Forms and reworked to Caboodle.
Starting point.
=> Initial attempt at contribution, submission docs, and templates

DeviceTests/Caboodle.DeviceTests.Shared/Preferences_Tests.cs
Adding more device tests for Preferences
=> Additional Preferences Device Tests

.editorconfig, DeviceTests/Caboodle.DeviceTests.Shared/Preferences_Tests.cs
=> Fixing the build.PR to fix the build

CONTRIBUTING.md
Adds information about mdoc and how to use our build targets.
=> GH-69: Updated CONTRIBUTING.md with mdoc information

Caboodle/Battery/Battery.android.cs, Caboodle/Battery/Battery.ios.cs, Caboodle/Battery/Battery.shared.cs, Caboodle/Battery/Battery.uwp.cs, Caboodle/DeviceInfo/DeviceInfo.android.cs, Caboodle/DeviceInfo/DeviceInfo.ios.cs, Caboodle/DeviceInfo/DeviceInfo.netstandard.cs, Caboodle/DeviceInfo/DeviceInfo.shared.cs, Caboodle/DeviceInfo/DeviceInfo.uwp.cs, DeviceTests/Caboodle.DeviceTests.Shared/DeviceInfo_Tests.cs, DeviceTests/Caboodle.DeviceTests.Shared/Utils.cs, Samples/Caboodle.Samples/ViewModel/DeviceInfoViewModel.cs
Let the consumer of the library control the threads. Just throw if on the wrong thread.
=> Change Threading

Caboodle.Tests/Clipboard_Tests.cs, Caboodle/Clipboard/Clipboard.android.cs, Caboodle/Clipboard/Clipboard.ios.cs, Caboodle/Clipboard/Clipboard.netstandard.cs, Caboodle/Clipboard/Clipboard.uwp.cs, DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems, DeviceTests/Caboodle.DeviceTests.Shared/Clipboard_Tests.cs, Samples/Caboodle.Samples/View/ClipboardPage.xaml, Samples/Caboodle.Samples/View/ClipboardPage.xaml.cs, Samples/Caboodle.Samples/ViewModel/ClipboardViewModel.cs, Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
=> GH-11: Add Clipboard API

Caboodle/Geocoding/Geocoding.android.cs, Caboodle/Geocoding/Geocoding.ios.cs, Caboodle/Geocoding/Geocoding.netstandard.cs, Caboodle/Geocoding/Geocoding.shared.cs, Caboodle/Geocoding/Geocoding.uwp.cs, Caboodle/Types/PlacemarkExtensions.android.cs, Caboodle/Types/PlacemarkExtensions.ios.cs, Caboodle/Types/PlacemarkExtensions.shared.cs, Caboodle/Types/PlacemarkExtensions.uwp.cs, docs/en/Microsoft.Caboodle/Geocoding.xml, docs/en/Microsoft.Caboodle/Location.xml, docs/en/Microsoft.Caboodle/LocationExtensions.xml, docs/en/Microsoft.Caboodle/Placemark.xml
Added documentation for geocoding #73 
Made methods internal where necessary.
=> GH-73: Add geocoding documentation

docs/en/Microsoft.Caboodle/Preferences.xml
Added mdocs for existing Preferences.
=> GH-73: Added docs for Preferences

Caboodle/Caboodle.csproj
Changed the NuGet author.
- Related to issue #90
None.
The changes just the package name.
=> GH-90: Changed the project/NuGet author

README.md
=> Update contributing based on feedback.

Caboodle/PhoneDialer/PhoneDialer.android.cs, Caboodle/Platform/Platform.android.cs, Caboodle/Sms/Sms.android.cs
User proper apis and fallback to regular intents. 
- Related to issue #113 
None! It works :)
=> GH-113 Fix Sms to user proper API. Tested on device. Updated api level helpers

Samples/Caboodle.Samples/ViewModel/BrowserViewModel.cs
=> Fix Browser Sample Picker

docs/en/Microsoft.Caboodle/Browser.xml, docs/en/Microsoft.Caboodle/BrowserLaunchType.xml, docs/en/Microsoft.Caboodle/PermissionException.xml, docs/en/Microsoft.Caboodle/Platform.xml, docs/en/index.xml
There were some docs changes that need to happen for existing code in master.
=> Fix up docs

Samples/Samples/App.xaml.cs, Xamarin.Essentials/VersionTracking/VersionTracking.shared.cs, docs/en/Xamarin.Essentials/VersionTracking.xml
Since we need to initialize it anyways we need to give a way for users to always call track to ensure current info is up to date.
Added: 
- void VersionTracking.Track();
=> Add Track to Version Tracking

Xamarin.Essentials/mdoc.targets, docs/en/FrameworksIndex/Xamarin.Essentials.Android.xml, docs/en/FrameworksIndex/Xamarin.Essentials.UWP.xml, docs/en/FrameworksIndex/Xamarin.Essentials.iOS.xml, docs/en/FrameworksIndex/Xamarin.Essentials.xml, docs/en/Xamarin.Essentials/Browser.xml, docs/en/Xamarin.Essentials/PermissionException.xml, docs/frameworks.xml
Docs need to use a more friendly name.
- Related to issue https://github.com/mono/api-doc-tools/issues/224
None.
None.
=> Updating docs to work around mdoc bug

Xamarin.Essentials/SecureStorage/SecureStorage.uwp.cs
Removed the ConfigureAwait(false) until further review can be done.
- Related to issue #133
None
None.
=> GH-133: Remove the ConfigureAwait(false)

DeviceTests/build.cake
Previously if device tests failed to run or complete, the listener would wait indefinitely, timing out the build.  Now the listener will time out after the specified amount (60 seconds by default) so the build can fail faster.
=> [DeviceTests] Timeout tcp listener

docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/FeatureNotSupportedException.xml, docs/en/Xamarin.Essentials/Geolocation.xml, docs/en/Xamarin.Essentials/GeolocationAccuracy.xml, docs/en/Xamarin.Essentials/GeolocationRequest.xml, docs/en/Xamarin.Essentials/GyroscopeChangedEventArgs.xml, docs/en/Xamarin.Essentials/GyroscopeData.xml, docs/en/Xamarin.Essentials/Location.xml, docs/en/Xamarin.Essentials/Magnetometer.xml, docs/en/Xamarin.Essentials/MagnetometerData.xml, docs/en/Xamarin.Essentials/NetworkAccess.xml, docs/en/Xamarin.Essentials/NotImplementedInReferenceAssemblyException.xml
Updating the docs.
- Related to issue #137 
None.
Just updating docs.
=> GH-137: Make sure the API docs are up to date

Samples/Samples.Android/Properties/AndroidManifest.xml, Samples/Samples/ViewModel/AccelerometerViewModel.cs, Samples/Samples/ViewModel/BaseViewModel.cs, Samples/Samples/ViewModel/CompassViewModel.cs, Samples/Samples/ViewModel/GeolocationViewModel.cs, Samples/Samples/ViewModel/GyroscopeViewModel.cs, Samples/Samples/ViewModel/HomeViewModel.cs, Samples/Samples/ViewModel/MagnetometerViewModel.cs, Samples/Samples/ViewModel/PhoneDialerViewModel.cs, Samples/Samples/ViewModel/SecureStorageViewModel.cs, Samples/Samples/ViewModel/SmsViewModel.cs, Xamarin.Essentials/AppInfo/AppInfo.android.cs, Xamarin.Essentials/Battery/Battery.android.cs, Xamarin.Essentials/Browser/Browser.android.cs, Xamarin.Essentials/Connectivity/Connectivity.android.cs, Xamarin.Essentials/DataTransfer/DataTransfer.android.cs, Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs, Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs, Xamarin.Essentials/Email/Email.android.cs, Xamarin.Essentials/FileSystem/FileSystem.android.cs, Xamarin.Essentials/Geocoding/Geocoding.android.cs, Xamarin.Essentials/Geolocation/Geolocation.android.cs, Xamarin.Essentials/Permissions/Permissions.android.cs, Xamarin.Essentials/PhoneDialer/PhoneDialer.android.cs, Xamarin.Essentials/Platform/Platform.android.cs, Xamarin.Essentials/SecureStorage/SecureStorage.android.cs, Xamarin.Essentials/SecureStorage/SecureStorage.shared.cs, Xamarin.Essentials/Sms/Sms.android.cs
Fix up sensor samples to re-subscribe on onappearing
Remove the old CurrentContext and use AppContext (fixes issues with receivers)
Fixed casting issues with android geolocation when using GPS
Added cancellation token on geolocation page when backing out.
- Related to issue #208, #207, #206, #204
=> GH-208,207,206,204 Multiple Fixes to sample application

README.md
=> Update Readme with Installation information.

DeviceTests/DeviceTests.Shared/DeviceTests.Shared.projitems, DeviceTests/DeviceTests.Shared/Platform_Tests.cs, Xamarin.Essentials/Platform/Platform.android.cs, Xamarin.Essentials/Platform/Platform.ios.cs, Xamarin.Essentials/Platform/Platform.netstandard.cs, Xamarin.Essentials/Platform/Platform.shared.cs, Xamarin.Essentials/Platform/Platform.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/OrientationSensor.xml, docs/en/Xamarin.Essentials/OrientationSensorChangedEventArgs.xml, docs/en/Xamarin.Essentials/OrientationSensorChangedEventHandler.xml, docs/en/Xamarin.Essentials/OrientationSensorData.xml, docs/en/Xamarin.Essentials/Platform.xml, docs/en/index.xml
- Related to issue #240
Added: 
- bool- boolPlatform.IsMainThread { get; } 
Changed:
- Update iOS/Android/UWP APIs to properly use new API
=> GH-240 Add IsMainThread detection API

DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs, DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj, DeviceTests/DeviceTests.iOS/Entitlements.plist, Samples/Samples.iOS/Entitlements.plist, Samples/Samples.iOS/Samples.iOS.csproj
=> iOS secure storage simulator tests (#247)

DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj, DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml, DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj, DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj, Samples/Samples.Android/Properties/AndroidManifest.xml, Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.UWP/Samples.UWP.csproj, Samples/Samples.iOS/Samples.iOS.csproj, Samples/Samples/Samples.csproj, Xamarin.Essentials/Vibration/Vibration.android.cs, Xamarin.Essentials/Xamarin.Essentials.csproj
Update Support Packages, Forms, and Reference Vectors
- Related to issue #254 
Added: 
Changed:
=> GH-254 Update Support Packages, Forms, and Reference Vectors

DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj, DeviceTests/DeviceTests.Android/Resources/Resource.designer.cs, DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj, DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj, Samples/Samples.Android/Resources/Resource.designer.cs, Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.UWP/Samples.UWP.csproj, Samples/Samples.iOS/Samples.iOS.csproj, Samples/Samples/Samples.csproj, Xamarin.Essentials/Xamarin.Essentials.csproj
Update nuget packages (support, mdoc, and forms)
- Related to issue #310
=> GH-310 Update NuGet packages

DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj, DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj, DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj, Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.UWP/Samples.UWP.csproj, Samples/Samples.iOS/Samples.iOS.csproj, Samples/Samples/Samples.csproj, Xamarin.Essentials/Xamarin.Essentials.csproj
Updating the NuGet versions and cleaned the project files.
- Related to issue #310 
None.
None.
=> GH-310: Updated Dependencies

Samples/Samples/ViewModel/GeolocationViewModel.cs, Xamarin.Essentials/Types/Location.shared.cs, Xamarin.Essentials/Types/LocationExtensions.android.cs, Xamarin.Essentials/Types/LocationExtensions.ios.cs, Xamarin.Essentials/Types/LocationExtensions.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Location.xml
- Related to issue #294
Added: 
- string - double? Location.Altitude { get; set; }
=> GH-294 Add altitude to location if available.

CONTRIBUTING.md
=> dotnet foundation CLA broken link

docs/en/ns-Xamarin.Essentials.xml
=> Fix spelling mistake

README.md
Update for #339 to clarify what developers need when installing
=> GH-339 Update README.md with Build Steps

Xamarin.Essentials/Accelerometer/Accelerometer.android.cs, Xamarin.Essentials/Accelerometer/Accelerometer.ios.cs, Xamarin.Essentials/Accelerometer/Accelerometer.shared.cs, Xamarin.Essentials/Battery/Battery.android.cs, Xamarin.Essentials/Battery/Battery.ios.cs, Xamarin.Essentials/Battery/Battery.shared.cs, Xamarin.Essentials/Battery/Battery.uwp.cs, Xamarin.Essentials/Compass/Compass.android.cs, Xamarin.Essentials/Compass/Compass.ios.cs, Xamarin.Essentials/Compass/Compass.shared.cs, Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs, Xamarin.Essentials/Gyroscope/Gyroscope.android.cs, Xamarin.Essentials/Gyroscope/Gyroscope.ios.cs, Xamarin.Essentials/Gyroscope/Gyroscope.shared.cs, Xamarin.Essentials/Magnetometer/Magnetometer.android.cs, Xamarin.Essentials/Magnetometer/Magnetometer.ios.cs, Xamarin.Essentials/Magnetometer/Magnetometer.shared.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.android.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.ios.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.shared.cs, Xamarin.Essentials/Types/SensorSpeed.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/BatteryPowerSource.xml, docs/en/Xamarin.Essentials/SensorSpeed.xml
Follow proper acronym guidance to use UI not Ui.
- Related to issue #367
Changed:
- - enum - SensorSpeed.Ui -> SensorSpeed.UI
- enum - BatteryPowerSource.Ac -> BatteryPowerSource.AC
None
=> GH-367 Change Ui to UI & Ac to AC

docs/en/Xamarin.Essentials/Gyroscope.xml
=> Fix the typo from gyrpscope >> gyroscope

DeviceTests/DeviceTests.Shared/DeviceTests.Shared.projitems, DeviceTests/DeviceTests.Shared/Launcher_Tests.cs, Samples/Samples/View/LauncherPage.xaml, Samples/Samples/View/LauncherPage.xaml.cs, Samples/Samples/ViewModel/HomeViewModel.cs, Samples/Samples/ViewModel/LauncherViewModel.cs, Xamarin.Essentials/Browser/Browser.android.cs, Xamarin.Essentials/Browser/Browser.ios.cs, Xamarin.Essentials/Browser/Browser.uwp.cs, Xamarin.Essentials/Launcher/Launcher.android.cs, Xamarin.Essentials/Launcher/Launcher.ios.cs, Xamarin.Essentials/Launcher/Launcher.netstandard.cs, Xamarin.Essentials/Launcher/Launcher.shared.cs, Xamarin.Essentials/Launcher/Launcher.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Launcher.xml, docs/en/index.xml
- Related to issue #356
Added: 
Changed:
=> GH-250 Implement Launcher API (#356)

Xamarin.Essentials/Vibration/Vibration.android.cs, Xamarin.Essentials/Xamarin.Essentials.csproj
Alight nuget versions to xamarin.forms.
Added: 
Changed:
=> Enable multi-target for Android API 25,26,27

Xamarin.Essentials/Preferences/Preferences.shared.cs, Xamarin.Essentials/SecureStorage/SecureStorage.shared.cs, Xamarin.Essentials/VersionTracking/VersionTracking.shared.cs, nugetreadme.txt
Since we can reset and clear out preferences we need to store them in unique places.
This will reset the SecureStorage and VersionTracking information on Android.
=> Create unique preference storage for each feature.

Xamarin.Essentials/Types/Location.shared.cs, Xamarin.Essentials/Types/LocationExtensions.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Location.xml, docs/en/Xamarin.Essentials/LocationExtensions.xml
=> Add more extensions for location

Xamarin.Essentials/Xamarin.Essentials.csproj
- Related to issue #467
Added: 
Changed:
=> GH-467: Update to 27.0.2.1

Samples/Samples/View/MapsPage.xaml, Samples/Samples/ViewModel/MapsViewModel.cs, Xamarin.Essentials/Maps/MapDirectionsMode.shared.cs, Xamarin.Essentials/Maps/MapLaunchOptions.shared.cs, Xamarin.Essentials/Maps/Maps.android.cs, Xamarin.Essentials/Maps/Maps.ios.cs, Xamarin.Essentials/Maps/Maps.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/MapDirectionsMode.xml, docs/en/Xamarin.Essentials/Maps.xml, docs/en/Xamarin.Essentials/MapsLaunchOptions.xml
Implement UWP navigation modes and also fix iOS navigation.
Added "none" mode.
- Related to issue #440
Added: 
- enum - enum MapDirectionsMode.None { get; set; } 
=> GH-440 Fix iOS Navigation & UWP/Android Navigation too!

Xamarin.Essentials/Xamarin.Essentials.csproj, nugetreadme.txt
Update release notes and make the project show all files with new .net sdk
=> Prep for 0.10.0-preview

.openpublishing.publish.config.json
=> [Work Around Build Issue] Use specified version of ECMA2Yaml to work around

DeviceTests/DeviceTests.Shared/Geolocation_Tests.cs, Samples/Samples/ViewModel/GeolocationViewModel.cs, Xamarin.Essentials/Types/Location.shared.cs, Xamarin.Essentials/Types/LocationExtensions.android.cs, Xamarin.Essentials/Types/LocationExtensions.ios.cs, Xamarin.Essentials/Types/LocationExtensions.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Location.xml
Align with proper naming for a DateTimeOffset
- Related to issue #522 
Changed:
- DateTimeOffset Location.TimestampUtc => object Location.Timestamp
None.
=> Change name to Timestamp.

Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.Android/proguard.cfg
Reference progaurd file.
- Related to issue #515
=> Add progaurd file for reference

Xamarin.Essentials/AssemblyInfo/AssemblyInfo.shared.cs, Xamarin.Essentials/Xamarin.Essentials.csproj, Xamarin.Essentials/mdoc.targets, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/AccelerometerData.xml, docs/en/Xamarin.Essentials/BarometerData.xml, docs/en/Xamarin.Essentials/BatteryChangedEventArgs.xml, docs/en/Xamarin.Essentials/CompassData.xml, docs/en/Xamarin.Essentials/ConnectivityChangedEventArgs.xml, docs/en/Xamarin.Essentials/FeatureNotEnabledException.xml, docs/en/Xamarin.Essentials/GeolocationRequest.xml, docs/en/Xamarin.Essentials/GyroscopeData.xml, docs/en/Xamarin.Essentials/Location.xml, docs/en/Xamarin.Essentials/MagnetometerData.xml, docs/en/Xamarin.Essentials/MapDirectionsMode.xml, docs/en/Xamarin.Essentials/Maps.xml, docs/en/Xamarin.Essentials/OrientationSensorData.xml, docs/en/Xamarin.Essentials/Placemark.xml, docs/en/Xamarin.Essentials/ScreenMetrics.xml, docs/en/Xamarin.Essentials/SmsMessage.xml, docs/en/Xamarin.Essentials/TextToSpeech.xml, docs/en/index.xml
Fixing the script and re-ran the docs.
This should technically be run as often as possible and before a PR can be merged. Very easy:
```
msbuild /restore /p:Configuration=Release /t:build;MDocUpdateDocs Xamarin.Essentials
```
If for some reason you can't build two targets at once, this can be done in two steps:
```
msbuild /restore /p:Configuration=Release /t:build Xamarin.Essentials
msbuild /p:Configuration=Release /t:MDocUpdateDocs Xamarin.Essentials
```
=> Regenerate the docs

README.md
Fixed a few things in the README:
* Fixed some comma and hyphen issues.
* Added link to up-for-grab issues where referenced.
* Updated the Markdown syntax to appease the Markdown linter that is part of the [Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack), mostly around header/list whitespace and unordered list syntax consistentcy.
=> README: Markdown and edit fixes.

Xamarin.Essentials/Xamarin.Essentials.csproj
=> Update release notes url

DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj, DeviceTests/DeviceTests.Shared/DeviceTests.Shared.csproj, DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj, DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj, README.md, Samples/Samples.Android/Resources/Resource.designer.cs, Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.Android/appcenter-post-clone.sh, Samples/Samples.UWP/Samples.UWP.csproj, Samples/Samples.iOS/AppDelegate.cs, Samples/Samples.iOS/Info.plist, Samples/Samples.iOS/Samples.iOS.csproj, Samples/Samples/App.xaml.cs, Samples/Samples/Helpers/CommonConstants.cs, Samples/Samples/Samples.csproj, Tests/Tests.csproj, Xamarin.Essentials/Xamarin.Essentials.csproj, appcenter-post-clone.sh
In Sample app for release builds integrate in the SDK
=> Integrate App Center SDK into Sample App

Xamarin.Essentials/TextToSpeech/TextToSpeech.android.cs, Xamarin.Essentials/TextToSpeech/TextToSpeech.ios.cs, Xamarin.Essentials/TextToSpeech/TextToSpeech.uwp.cs
fix NRE. 
- Related to issue #587
none
none
=> Fix GH-587- added checks for Locale before accessing

DeviceTests/DeviceTests.Shared/Geocoding_Tests.cs, Samples/Samples.UWP/MainPage.xaml.cs, Samples/Samples/App.xaml.cs, Xamarin.Essentials/Geocoding/Geocoding.shared.cs, Xamarin.Essentials/Geocoding/Geocoding.uwp.cs, Xamarin.Essentials/Platform/Platform.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Geocoding.xml, docs/en/Xamarin.Essentials/Platform.xml
=> Change MapKey to Platform.MapServiceToken only for UWP

DeviceTests/DeviceTests.Shared/Connectivity_Tests.cs, Samples/Samples/View/ConnectivityPage.xaml, Samples/Samples/ViewModel/ConnectivityViewModel.cs, Tests/Connectivity_Tests.cs, Xamarin.Essentials/Connectivity/Connectivity.android.cs, Xamarin.Essentials/Connectivity/Connectivity.ios.cs, Xamarin.Essentials/Connectivity/Connectivity.netstandard.cs, Xamarin.Essentials/Connectivity/Connectivity.shared.cs, Xamarin.Essentials/Connectivity/Connectivity.shared.enums.cs, Xamarin.Essentials/Connectivity/Connectivity.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/ConnectionProfile.xml, docs/en/Xamarin.Essentials/Connectivity.xml, docs/en/Xamarin.Essentials/ConnectivityChangedEventArgs.xml
got rid of Other made it u…nknown, removed WiMAX and updated Profiles to ConnectionProfiles
- Related to issue #570
=> GH-570: Updates Connectivity APIs from the review! 

Xamarin.Essentials/Browser/Browser.android.cs, Xamarin.Essentials/Browser/Browser.ios.cs, Xamarin.Essentials/Browser/Browser.netstandard.cs, Xamarin.Essentials/Browser/Browser.shared.cs, Xamarin.Essentials/Browser/Browser.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Browser.xml, docs/en/Xamarin.Essentials/BrowserLaunchMode.xml
See https://github.com/xamarin/Essentials/issues/568
=> GH-568: [api-fix] Browser

Xamarin.Essentials/DeviceInfo/DeviceInfo.netstandard.cs, Xamarin.Essentials/DeviceInfo/DeviceInfo.shared.cs
Makes it easy to check if running in correct platform.
- Related to issue #619
Added: 
Changed:
=> GH-619: Return Unknown for Platform/Idiom in .NET Standard

Xamarin.Essentials/AppInfo/AppInfo.ios.cs, Xamarin.Essentials/Permissions/Permissions.android.cs, Xamarin.Essentials/Permissions/Permissions.ios.cs, Xamarin.Essentials/Permissions/Permissions.shared.cs, Xamarin.Essentials/Permissions/Permissions.uwp.cs
- Only check UI thread for permission requests when absolutely necessary: Fixes #621
=> GH-621 Fixes Main thread checks for permissions.

docs/en/docfx.json
Update global metadata to help with reporting.
Add feedback box to end of API doc pages.
None
None
None
=> [docs] Update global metadata for API docs

.github/PULL_REQUEST_TEMPLATE.md, DeviceTests/DeviceTests.Shared/Connectivity_Tests.cs, README.md, Xamarin.Essentials/Connectivity/Connectivity.android.cs, Xamarin.Essentials/Connectivity/Connectivity.shared.cs, Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs, Xamarin.Essentials/GlobalSuppressions.shared.cs, Xamarin.Essentials/Permissions/Permissions.android.cs, Xamarin.Essentials/Permissions/Permissions.ios.cs, Xamarin.Essentials/Permissions/Permissions.uwp.cs, Xamarin.Essentials/Sms/Sms.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/SmsMessage.xml, docs/en/docfx.json, nugetreadme.txt
=> Live update

Samples/Samples/View/BrowserPage.xaml, Samples/Samples/ViewModel/BrowserViewModel.cs, Xamarin.Essentials/Browser/Browser.android.cs, Xamarin.Essentials/Browser/Browser.ios.cs, Xamarin.Essentials/Browser/Browser.netstandard.cs, Xamarin.Essentials/Browser/Browser.shared.cs, Xamarin.Essentials/Browser/Browser.uwp.cs, Xamarin.Essentials/Browser/BrowserLaunchMode.shared.cs, Xamarin.Essentials/Browser/BrowserLaunchOptions.shared.cs, Xamarin.Essentials/Browser/BrowserTitleMode.shared.cs, Xamarin.Essentials/Types/PlatformExtensions/ColorExtensions.shared.cs, Xamarin.Essentials/Xamarin.Essentials.csproj, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Browser.xml, docs/en/Xamarin.Essentials/BrowserLaunchOptions.xml, docs/en/Xamarin.Essentials/BrowserTitleMode.xml, docs/en/Xamarin.Essentials/ColorExtensions.xml, docs/en/Xamarin.Essentials/TextToSpeech.xml, docs/en/index.xml
- Related to issue #196
Added: 
Changed:
```csharp
}
```
=> GH-196 Browser Customization 

CONTRIBUTING.md, Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs
iOS:  if we get a duplicate item try to remove and then re-add if possible.
- Related to issue #704
=> GH-704 Handle duplicate item in keychain

azure-pipelines.yml
Added: 
Changed:
```csharp
}
```
=> Use more explicit job definitions

CONTRIBUTING.md, Xamarin.Essentials/Connectivity/Connectivity.android.cs
- Related to issue #698
Added: 
Changed:
```csharp
}
```
=> GH-698 Set longer delay on connectivity changes - Android

Samples/Samples/ViewModel/BrowserViewModel.cs
=> Simple fix for browser sample

Xamarin.Essentials/SecureStorage/SecureStorage.android.cs
- Related to issue #709
Added: 
Changed:
```csharp
}
```
=> Lock keystore on Android for cipher

DeviceTests/build.cake, Tests/Share_Tests.cs, Tests/Tests.csproj, azure-pipelines.yml
Adding the Device Tests to the yaml
=> [WIP] Adding the Device Tests to the yaml

DeviceTests/DeviceTests.Shared/Email_Tests.cs, Xamarin.Essentials/Email/Email.uwp.cs
- Related to issue #707
Don't add blank emails to UWP.
=> Don't add empty strings on UWP to email

Samples/Samples.Android/Resources/Resource.designer.cs, Xamarin.Essentials/Platform/Platform.android.cs, Xamarin.Essentials/Types/FileProvider.android.cs
…ic cache director and use correct path for file provider.
- Related to issue #788
None pre-N devices with files in internal cache directory we must copy it to public since it doesn't use file provider.
For pre-n devices we must
=> GH-788 -> Fix for Pre-N devices for file sharing

DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs, Xamarin.Essentials/SecureStorage/SecureStorage.android.cs
- Related to issue #771
None
Will return true now when we remove the key from android
=> Fixes #771 - Add test for remove SS and fix android return value

Samples/Samples/ViewModel/TextToSpeechViewModel.cs
None
Added: 
Changed:
```csharp
}
```
=> Cleanup vm for TTS

Xamarin.Essentials/Permissions/Permissions.ios.cs
Just doing some more null checks on auth callbacks. Shouldn't happen, but let's check for them :)
- Related to issue #740
None
=> Add more null checks in LocationAuthCallback Should Fix #740

Samples/Samples/View/EmailPage.xaml, Samples/Samples/ViewModel/EmailViewModel.cs, Xamarin.Essentials/Email/Email.android.cs, Xamarin.Essentials/MainThread/MainThread.uwp.cs
Have to use a different intent for multiple attachments :(
- Related to issue #800 
none.
=> GH-800: Fix Multi-attachment on Android emails

Xamarin.Essentials/TextToSpeech/TextToSpeech.android.cs
Always use one else may get mixed results on different devices :(
- Related to issue #786
None
=> Fixes #786, set the speach rate to 1 always. (Android)

Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs
- Related to issue #817
Added: 
Changed:
```csharp
}
```
=> GH-817: Try catch the uimode manager

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/new-api-spec.md
This templates are derived from the Xamarin.Form templates
=> Created Issue_Templates for creating issues

.github/ISSUE_TEMPLATE/bug-report.md
Fixed issue with the bug template and an invalid label
=> Fixed issue with the bug template and an invalid label

Samples/Samples/View/LauncherPage.xaml, Xamarin.Essentials/Sms/Sms.ios.cs
- Related to issue #807
Added: 
Changed:
```csharp
}
```
=> Fixes #807 Put TrySetResult

Xamarin.Essentials/Launcher/Launcher.shared.cs
Fixed #861 wrong ExperimentalFeatures check in Launcher.OpenAsync
=> Fixed wrong ExperimentalFeatures check in Launcher.OpenAsync

nugetreadme.txt
Use HTTPS URLs in readme.txt that's in the Xamarin Essentials NuGet package.
N/A
None
None
=> Update NuGet readme.txt URLs to use HTTPS

DeviceTests/DeviceTests.Shared/DeviceTests.Shared.csproj, DeviceTests/build.cake, Xamarin.Essentials/Xamarin.Essentials.csproj, azure-pipelines.yml
=> Cleanup the PR for fixing build

DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj, DeviceTests/DeviceTests.Shared/DeviceTests.Shared.csproj, Samples/Samples.Android/Samples.Android.csproj, Xamarin.Essentials/Xamarin.Essentials.csproj
Xamarin.Android Support 28.0.0.3 is soon available, bumping to ensure compatibility
=> Bump to 28.0.0.3 of support

CodeStyles.targets, DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj, DeviceTests/DeviceTests.Android/Resources/Resource.designer.cs, DeviceTests/DeviceTests.Shared/DeviceTests.Shared.csproj, DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj, DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj, Samples/Samples.Android/Resources/Resource.designer.cs, Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.Tizen/CustomViewCellRenderer.cs, Samples/Samples.UWP/Samples.UWP.csproj, Samples/Samples.iOS/Samples.iOS.csproj, Samples/Samples/Samples.csproj, Samples/Samples/ViewModel/SmsViewModel.cs, Tests/Tests.csproj, Xamarin.Essentials.sln, Xamarin.Essentials/Xamarin.Essentials.csproj, azure-pipelines.yml
Fix reference to Mobile Extensions on UWP.
Updating nuget packages on just about everything
- Related to issue #904
=> Update all nuget packages and also fixes #904

Xamarin.Essentials/Xamarin.Essentials.csproj, nuget.config
Should now be able to pull code, open sln, and build correctly.
- Related to issue #947 
Added: 
Changed:
```csharp
}
```
=> VS for Mac Multi-target support

DeviceTests/DeviceTests.Android/Tests/FileProvider_Tests.cs, DeviceTests/DeviceTests.Shared/Geolocation_Tests.cs, DeviceTests/DeviceTests.Shared/HardwareSupport.cs, DeviceTests/DeviceTests.Shared/Permissions_Tests.cs, Xamarin.Essentials/Platform/Platform.android.cs
Added: 
Changed:
```csharp
}
```
=> Cleanup permissions check for Geolocation

Xamarin.Essentials/Xamarin.Essentials.csproj, azure-pipelines.yml
- Related to issue #990
Added: 
Changed:
```csharp
}
```
=> Fixes #990 - only pull in utils when needed

Samples/Samples/Samples.csproj, Samples/Samples/View/ColorConvertersPage.xaml, Samples/Samples/View/ColorConvertersPage.xaml.cs, Samples/Samples/ViewModel/ColorConvertersViewModel.cs, Samples/Samples/ViewModel/HomeViewModel.cs
Validates that the linker is working alright with color converters. Nice samples :)
=> Add color converter samples :)

Samples/Samples/ViewModel/ColorConvertersViewModel.cs, Tests/Color_Tests.cs, Xamarin.Essentials/Types/ColorConverters.shared.cs, Xamarin.Essentials/Types/PlatformExtensions/ColorExtensions.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-tvos.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials-watchos.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/ColorConverters.xml, docs/en/Xamarin.Essentials/ColorExtensions.xml
- Related to issue #1037
Added: 
Changed:
```csharp
}
```
=> GH-1036 Make GetComplementary an extension

Xamarin.Essentials/Geocoding/Geocoding.uwp.cs
=> Add more info about MST

Xamarin.Essentials/Permissions/Permissions.android.cs
- Related to issue #1051
Added: 
Changed:
```csharp
}
```
=> Fixes #1051  Make sure CheckStatusAsync works property on Android

Xamarin.Essentials/Types/LocationExtensions.android.cs
- Related to issue #1069
Added: 
Changed:
```csharp
}
```
=> GH-1069 - Add check for JellyBeanMr2 for FromMockProvider

azure-pipelines.yml
Added: 
Changed:
```csharp
}
```
=> Use iOS 13.3 :) for simulator

Xamarin.Essentials/WebAuthenticator/AppleSignInAuthenticator.ios.cs, Xamarin.Essentials/WebAuthenticator/AppleSignInAuthenticator.netstandard.android.tvos.watchos.uwp.tizen.cs, Xamarin.Essentials/WebAuthenticator/AppleSignInAuthenticator.shared.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticatorResult.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-tvos.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials-watchos.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/AppleSignInAuthenticator+Options.xml, docs/en/Xamarin.Essentials/AppleSignInAuthenticator.xml, docs/en/Xamarin.Essentials/WebAuthenticator.xml, docs/en/Xamarin.Essentials/WebAuthenticatorCallbackActivity.xml, docs/en/Xamarin.Essentials/WebAuthenticatorResult.xml, docs/en/index.xml
It's a nested type already, so the shorter name is a bit less verbose and more clean looking :)
=> Rename apple signin options

README.md, android-setup.ps1
Add an awesome script to setup Android environment
=> Android setup Script

Xamarin.Essentials/Connectivity/Connectivity.uwp.cs
Getting Network adapter apparently may throw a com exception, so try/catch that.
- Related to issue #1078
None
Will return unknown now.
=> GH-1078 Try catch getting Network Adapter and only query it once. (UWP)

Xamarin.Essentials/Xamarin.Essentials.csproj
=> Fixes #1128 - Update Xamarin.Essentials.csproj with new type swizzle

Xamarin.Essentials/Launcher/Launcher.shared.cs
- Related to issue #1123
Added: 
Changed:
```csharp
}
```
=> Fixes #1123

DeviceTests/DeviceTests.Android/Tests/FileProvider_Tests.cs
Fixes compiling FileProvider_Tests in the dev/file-picker branch.
- none
None
None.
=> FilePicker branch: fixed FileProvider_Tests

Xamarin.Essentials/Platform/Platform.ios.tvos.watchos.cs
- Related to issue #1121
Added: 
Changed:
```csharp
}
```
=> GH-1121: Don't throw if window is not found.

Samples/Sample.Server.WebAuthenticator/Startup.cs
Fix build, it is made about namespace ordering lol
=> Fix ordering for build!

Xamarin.Essentials/PhoneDialer/PhoneDialer.android.cs
Fix a regression on some phones when extensions aren't there.
- Related to issue #1179
Hopefully fixes formatting.
=> GH-1179 - Add check to encode number only when there is an extension.

Samples/Samples.iOS/Samples.iOS.csproj
This is just for app center builds
=> Link in release simualtor mode for testing

DeviceTests/DeviceTests.Shared/DeviceTests.Shared.csproj, DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj, Samples/Sample.Server.WebAuthenticator/Sample.Server.WebAuthenticator.csproj, Samples/Samples.Android/Resources/values/styles.xml, Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.UWP/Samples.UWP.csproj, Samples/Samples.iOS/Samples.iOS.csproj, Samples/Samples/Samples.csproj, Xamarin.Essentials/Xamarin.Essentials.csproj
Samples now have full migration to AndroidX and latest Xamarin.Forms.
Device Tests still stuck on older XF, but updated a few references.
=> Update Latest NuGets

Xamarin.Essentials/WebAuthenticator/WebAuthenticator.ios.tvos.cs
WebAuthenticator's `ContextProvider` object implements
`IASWebAuthenticationPresentationContextProviding` interface
which is iOS 13 and up, since this is more of a native runtime
requirement we can use the AdoptsAttribute to tell the Objective-C
runtime via the `conformsToProtocol:` check that our object does
conform to the `ASWebAuthenticationPresentationContextProviding`
protocol.
There is no problem with iOS versions < 13.0 because this Objective-C
runtime check (runtime asking for conformance via `conformsToProtocol:`)
will only happen on iOS 13 and up.
None
None, should be identical.
=> [WebAuthenticator] Break iOS 13 dependency on WebAuthenticator

Samples/Samples.Android/proguard.cfg
... by amending proguard.cfg
- Related to issue #1198
None.
None.
=> fix a ClassNotFoundException when running Samples.Android

nugetreadme.txt
Minor change, but makes it more readable.
Made a small grammar fix (comma) on the readme.txt file. 
None
=> grammar fix

Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs
Update list of potential emulator products
=> Update checks for emulator based off latest Google recommendations

Samples/Samples.UWP/Package.appxmanifest, Xamarin.Essentials/Permissions/Permissions.uwp.cs, Xamarin.Essentials/Platform/Platform.uwp.cs
We used to do weird ! checks, just simplified it and brought in UAP namespace to do additional checks to. Added to sample project and working well.
None
=> GH-1201: Fix Capability Check should be || and added uap xmlns

Xamarin.Essentials/WebAuthenticator/WebAuthenticator.ios.tvos.cs
- Related to issue #1210
Added: 
Changed:
```csharp
}
```
=> GH-1210: Try to make AS&SF Static

Xamarin.Essentials/Flashlight/Flashlight.android.cs, Xamarin.Essentials/Geolocation/Geolocation.android.cs, Xamarin.Essentials/Geolocation/Geolocation.ios.cs, Xamarin.Essentials/Geolocation/Geolocation.tizen.cs, Xamarin.Essentials/Geolocation/Geolocation.uwp.cs, Xamarin.Essentials/Permissions/Permissions.ios.tvos.watchos.cs, Xamarin.Essentials/Permissions/Permissions.shared.cs
We used to do this before using the new api, so need ot do checks.
Also put in some null checks on locaiton manager for good measuere
- Related to issue #1238
Brings it back to expected behavior.
=> GH-1238: Fix permissions not throwing exception

CONTRIBUTING.md
Fixes dead link in CONTRIBUTING.md
=> Fix dead link to coding style in CONTRIBUTING.md

docs/en/docfx.json
Remove MSDN zip xref config from existing .NET repos
=> Remove MSDN zip xref config from existing .NET repos

Xamarin.Essentials/Xamarin.Essentials.csproj
Trying to see how to reference the nuget and less reference assemblies
- Related to issue #904
=> GH-904 Test - Drop system ref and add nuget.

Xamarin.Essentials/Xamarin.Essentials.csproj
Added: 
Changed:
```csharp
}
```
=> Remove Microsoft.NETCore.UniversalWindowsPlatform from the nuget

docs/en/Xamarin.Essentials/Accelerometer.xml
=> Fixed couple of small typos in accelerometer API docs

Tests/Share_Tests.cs, Xamarin.Essentials/Screenshot/Screenshot.uwp.cs
Fix a few UWP issues with the Screenshot API.
- Fixes #1448
- Fixes #1432
None.
=> Fix a few issues with the UWP Screenshot API

Xamarin.Essentials/TextToSpeech/TextToSpeech.android.cs
Since #1030  was not merged I decided to split it up in to smaller parts which can easily be merged without requiring much review. See #1030 for pr details. This pr contains simply  the enum check optimization (dont call object.equals on enums as they dont provide a enum specific override)
=> Optimmization in TTS.Android

Xamarin.Essentials/SecureStorage/SecureStorage.tizen.cs
Don't return a null Task but return a null result task.
- Fixes issue reported here: https://github.com/xamarin/Essentials/pull/1061#issuecomment-716481007
Added: 
Changed:
```csharp
}
```
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version …
=> Don't return a null Task

SignList.xml, azure-pipelines.yml
Use the new signing mechanisms
Added: 
Changed:
```csharp
}
```
=> Add v2 Signing

docs/en/Xamarin.Essentials/DisplayInfo.xml
Improve DisplayInfo docs
- Fixes #1474
None.
None.
=> Improve DisplayInfo docs

Samples/Samples.Android/Properties/AndroidManifest.xml, Samples/Samples.Android/Samples.Android.csproj
Added: 
Changed:
```csharp
}
```
=> Fix up package visibility

Samples/Samples.Tizen/Program.cs, Samples/Samples.Tizen/Samples.Tizen.csproj, Samples/Samples.Tizen/tizen-manifest.xml, Samples/Samples/App.xaml.cs, Xamarin.Essentials/Email/Email.tizen.cs, Xamarin.Essentials/Launcher/Launcher.tizen.cs, Xamarin.Essentials/Share/Share.tizen.cs, Xamarin.Essentials/Sms/Sms.tizen.cs, Xamarin.Essentials/Types/PlatformExtensions/ColorExtensions.tizen.cs, Xamarin.Essentials/Types/PlatformExtensions/PointExtensions.tizen.cs, Xamarin.Essentials/Types/PlatformExtensions/RectangleExtensions.tizen.cs, Xamarin.Essentials/Types/PlatformExtensions/SizeExtensions.tizen.cs
Fix Launcher for OpenFileRequest
Avoid AppActions for Tizen
Add Material reference
Add missing privilege for AppInfo.PlatformShowSettingsUI()
Add type extensions for Tizen
Change AppControlData string
=> [Tizen] Fix some issues

Xamarin.Essentials/FileSystem/FileSystem.tizen.cs, Xamarin.Essentials/MediaPicker/MediaPicker.tizen.cs
Added: 
Changed:
```csharp
}
```
=> Some fixes for Tizen

Xamarin.Essentials/Xamarin.Essentials.csproj
Use the correct version of OpenTK for macOS
- Fixes #1383
None.
None.
=> Use the correct version of OpenTK for macOS

Xamarin.Essentials/Permissions/Permissions.ios.cs
Use the static Create to properly detect a previous denied
- Fixes #1521
None.
None.
=> Use the static Create to properly detect a previous denied

Samples/Samples/View/BasePage.cs, Samples/Samples/View/ContactDetailsPage.xaml, Samples/Samples/View/ContactDetailsPage.xaml.cs, Samples/Samples/View/ContactsPage.xaml, Samples/Samples/ViewModel/BaseViewModel.cs, Samples/Samples/ViewModel/ContactDetailsViewModel.cs, Samples/Samples/ViewModel/ContactsViewModel.cs, Samples/Samples/ViewModel/ObservableObject.cs
Update the sample to better support the #1405 PR
=> Update the Contacts sample to have a details page

Xamarin.Essentials/Share/Share.android.cs
=> Fixes #1553 Android Share (check intent for > 1)

Xamarin.Essentials/Flashlight/Flashlight.android.cs
Catch those random exceptions in the camera for some Android devices.
- Fixes #1485
None
No crashes.
=> Fixes #1485 - Try/Catch TorchMode on Android

Xamarin.Essentials/FileSystem/FileSystem.android.cs
This PR has 2 changes:
1. Correctly handle the changed file permissions on Android 10+
2. Use the external storage for caching picked files if we can
- Fixes #1574
=> Some improvements to the Android pickers

Xamarin.Essentials/Browser/Browser.android.cs, Xamarin.Essentials/Xamarin.Essentials.csproj
Added: 
Changed:
```csharp
}
```
=> Updated Xamarin.AndroidX.Browser to 1.3.0

Xamarin.Essentials/Types/LocationExtensions.ios.tvos.watchos.macos.cs
This will allow the code to build in older VS versions
- Fixes #1589
None.
None.
=> Use manual selectors for new APIs

DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj, DeviceTests/DeviceTests.Shared/DeviceTests.Shared.csproj, DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj, DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj, Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.Mac/Samples.Mac.csproj, Samples/Samples.UWP/Samples.UWP.csproj, Samples/Samples.iOS/Samples.iOS.csproj, Samples/Samples/App.xaml, Samples/Samples/Samples.csproj, Tests/Tests.csproj
Update libraries and fix the issue where iOS text boxes have invisible text.
=> Update some libraries in the samples

DeviceTests/DeviceTests.Shared/Geocoding_Tests.cs, Samples/Samples/ViewModel/GeocodingViewModel.cs
Adding the country causes Apple to no longer find things?
=> Fix Tests and CI

Xamarin.Essentials/Connectivity/Connectivity.ios.tvos.macos.reachability.cs
- Related to issue #1613 
Added: 
Changed:
```csharp
}
```
=> Fixes #1613 only add WiFi if not celluar

Xamarin.Essentials/AssemblyInfo/AssemblyInfo.ios.tvos.watchos.macos.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticator.android.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticator.ios.tvos.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticator.macos.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticator.netstandard.watchos.tizen.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticator.shared.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticator.uwp.cs, azure-pipelines.yml
=> Implement prefersEphemeralWebBrowserSession Fixes #1712

Xamarin.Essentials/Xamarin.Essentials.csproj
Added: 
Changed:
```csharp
}
```
=> Bump AndroidX

docs/en/Xamarin.Essentials/FileBase.xml
This update of the documentation should make it easier to use the API. 
There should be fewer problems similar to #1746
=> Update docs about FileBase

Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs
try/catch getting display info
- Related to issue #1748
None
=> Fixes #1748 - try/catch getting display info

Xamarin.Essentials/PhoneDialer/PhoneDialer.android.cs
- Related to issue #1661 
None
=> Fixes #1661 use passed in phone as fallback if can't format

Xamarin.Essentials/Share/Share.ios.cs
Fixes #1896
Added: 
Changed:
```csharp
}
```
=> Set the PopoverPresentationController for files too

Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs
=> Fixed #1355 delay processing change so OS updates

azure-pipelines.yml, build.cake
Run only whats necessary for shipping Essentials.
None
None
=> [ci] Comply with EO 

docs/en/docfx.json
Enable build config to generate canonical URL with moniker
=> [SEO][Rollout Monikered Canonical]Add URL moniker

Xamarin.Essentials/Xamarin.Essentials.csproj
=> Update Xamarin.AndroidX.Browser dependency

README.md
Updating about .net 6 and 7 and maui stuff in docs. Thoughts?
=> Update info about Xamarin.Essentials in .NET 6

.github/ISSUE_TEMPLATE/customer-feedback.yml, docs/en/docfx.json
Enabling open source API docs feedback, because, well...reasons.
=> Enable open source docs feedback
