Caboodle/Caboodle.csproj
Add a blank TargetFrameworks so it loads that first and then loads the windows. Via the VS team :)
=> Fix loading issues of csproj on Windows

Caboodle/Preferences/Preferences.android.cs, Caboodle/Preferences/Preferences.ios.cs, Caboodle/Preferences/Preferences.uwp.cs
- Android/iOS: if the default value was `null`, then the `case string s` would not be true
- UWP: don't try using the shared name if it was null
=> Fixed bugs in the preferences

Caboodle/Types/LocationExtensions.shared.cs, build.ps1
Added a simple PowerShell script that just runs Msbuild to restore, build, and package the library. This is for the CI bots just to run `./build.ps1`.
It is also useful for verifying that all is well before submitting a PR.
=> Added a build script for CI bots

Samples/Caboodle.Samples/Caboodle.Samples.csproj
The referenced version of XF already provides targets for both removed snippets, see 
https://github.com/xamarin/Xamarin.Forms/blob/2.5.0/.nuspec/Xamarin.Forms.DefaultItems.targets#L11 and 
https://github.com/xamarin/Xamarin.Forms/blob/2.5.0/.nuspec/Xamarin.Forms.DefaultItems.props#L4.
=> Remove unnecessary MSBuilld snippets that already ship with XF

CONTRIBUTING.md
changed `_s` to `s_`
From [C# Coding Style](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md):
>We use \_camelCase for internal and private fields and use readonly where possible. Prefix instance fields with \_, static fields with s\_ and thread static fields with t\_. When used on static fields, readonly should come after static (i.e. static readonly not readonly static).
=> Minor text fix

Caboodle/Battery/Battery.shared.cs, Samples/Caboodle.Samples/View/BatteryPage.xaml, Samples/Caboodle.Samples/ViewModel/BatteryViewModel.cs, docs/en/Microsoft.Caboodle/Battery.xml, docs/en/Microsoft.Caboodle/BatteryChangedEventArgs.xml, docs/en/Microsoft.Caboodle/BatteryChangedEventHandler.xml, docs/en/Microsoft.Caboodle/BatteryPowerSource.xml, docs/en/Microsoft.Caboodle/BatteryState.xml
Add documentation for battery API for #73 
Changed:
- made the constructor of event args internal.
None
=> GH-73: Add Battery Documentation

Caboodle.Tests/Battery_Tests.cs, Caboodle.Tests/Clipboard_Tests.cs, Caboodle.Tests/Geocoding_Tests.cs, Caboodle.Tests/Preferences_Tests.cs, Caboodle/Battery/Battery.netstandard.cs, Caboodle/Clipboard/Clipboard.netstandard.cs, Caboodle/DeviceInfo/DeviceInfo.netstandard.cs, Caboodle/Geocoding/Geocoding.netstandard.cs, Caboodle/Platform/Platform.netstandard.cs, Caboodle/Preferences/Preferences.netstandard.cs, Caboodle/Shared/Exceptions.shared.cs
Fix big glaring type and add exception at the end
- Related to issue #82 
Changed to: NotImplementedInReferenceAssemblyException
=> GH-82: Fix type and add Exception for NotImplementedInReference

Caboodle/Battery/Battery.uwp.cs
Proper checks for when battery is full on UWP.
- Related to issue #88
Add checks for full when battery is Idle
=> GH-88 Fix for UWP battery when fully charged

Caboodle/AppInfo/AppInfo.android.cs, Caboodle/AppInfo/AppInfo.ios.cs, Caboodle/AppInfo/AppInfo.netstandard.cs, Caboodle/AppInfo/AppInfo.shared.cs, Caboodle/AppInfo/AppInfo.uwp.cs, Caboodle/DeviceInfo/DeviceInfo.android.cs, Caboodle/DeviceInfo/DeviceInfo.ios.cs, Caboodle/DeviceInfo/DeviceInfo.netstandard.cs, Caboodle/DeviceInfo/DeviceInfo.shared.cs, Caboodle/DeviceInfo/DeviceInfo.uwp.cs, Caboodle/Shared/Utils.shared.cs, DeviceTests/Caboodle.DeviceTests.Shared/DeviceInfo_Tests.cs, Samples/Caboodle.Samples/ViewModel/DeviceInfoViewModel.cs, docs/en/Microsoft.Caboodle/AppInfo.xml, docs/en/index.xml
Moved the app information properties into a new type called: `AppInfo`
- Related to issue #95
Added: 
```csharp
static class AppInfo {
static string PackageName { get; }
static string Name { get; }
static string VersionString { get; }
static Version Version { get; }
static string BuildString { get; }
```
Removed:
```csharp
static class DeviceInfo {
static string AppPackageName { get; }
static string AppName { get; }
static string AppVersionString { get; }
static Version AppVersion { get; }
static string AppBuildString { get; }
```
Moved the app-related properties from the `DeviceInfo` type into the `AppInfo` type.
=> GH-95: Moved app info into AppInfo

Caboodle/mdoc.targets, docs/en/Microsoft.Caboodle/Platform.xml
Only generate docs for Microsoft.Caboodle.dll.
- Related to issue #94
None.
Only changes to what assemblies are used to generate docs.
=> GH-94: Only generate docs for current assembly

Caboodle.Tests/Sms_Tests.cs, Caboodle/Platform/Platform.android.cs, Caboodle/Platform/Platform.ios.cs, Caboodle/Shared/Exceptions.shared.cs, Caboodle/Sms/Sms.android.cs, Caboodle/Sms/Sms.ios.cs, Caboodle/Sms/Sms.netstandard.cs, Caboodle/Sms/Sms.shared.cs, Caboodle/Sms/Sms.uwp.cs, DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems, DeviceTests/Caboodle.DeviceTests.Shared/Sms_Tests.cs, DeviceTests/Caboodle.DeviceTests.Shared/Utils.cs, Samples/Caboodle.Samples/App.xaml, Samples/Caboodle.Samples/Converters/NegativeConverter.cs, Samples/Caboodle.Samples/View/BasePage.cs, Samples/Caboodle.Samples/View/SMSPage.xaml, Samples/Caboodle.Samples/View/SMSPage.xaml.cs, Samples/Caboodle.Samples/ViewModel/BaseViewModel.cs, Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs, Samples/Caboodle.Samples/ViewModel/SmsViewModel.cs, docs/en/Microsoft.Caboodle/Sms.xml, docs/en/Microsoft.Caboodle/SmsMessage.xml, docs/en/index.xml
Adding the SMS API as designed in #26.
- Related to issue #26
Adding the SMS API as designed in #26.
=> GH-26: Add SMS API

Caboodle.Tests/DataTransfer_Tests.cs, Caboodle/DataTransfer/DataTransfer.android.cs, Caboodle/DataTransfer/DataTransfer.ios.cs, Caboodle/DataTransfer/DataTransfer.netstandard.cs, Caboodle/DataTransfer/DataTransfer.shared.cs, Caboodle/DataTransfer/DataTransfer.uwp.cs, Caboodle/Platform/Platform.ios.cs, Samples/Caboodle.Samples.Android/Caboodle.Samples.Android.csproj, Samples/Caboodle.Samples/Caboodle.Samples.csproj, Samples/Caboodle.Samples/View/DataTransferPage.xaml, Samples/Caboodle.Samples/View/DataTransferPage.xaml.cs, Samples/Caboodle.Samples/ViewModel/DataTransferViewModel.cs, Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs, docs/en/Microsoft.Caboodle/DataTransfer.xml, docs/en/Microsoft.Caboodle/ShareTextRequest.xml
Initial support for Share API aka Data Transfer. Leave API open to transferring of other types of data in the future.
- Related to issue #22
Added: 
- Task ShowShareUI(ShareTextRequest request)
- Task ShowShareUI(string text)
- Task ShowShareUI(string text, string title)
=> GH-22: Initial Support for Data Transfer aka Share

Caboodle.Tests/PhoneDialer_Tests.cs, Caboodle/Caboodle.csproj, Caboodle/PhoneDialer/PhoneDialer.android.cs, Caboodle/PhoneDialer/PhoneDialer.ios.cs, Caboodle/PhoneDialer/PhoneDialer.netstandard.cs, Caboodle/PhoneDialer/PhoneDialer.shared.cs, Caboodle/PhoneDialer/PhoneDialer.uwp.cs, Caboodle/Platform/Platform.android.cs, DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems, DeviceTests/Caboodle.DeviceTests.Shared/PhoneDialer_Tests.cs, DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP.csproj, Samples/Caboodle.Samples.UWP/Caboodle.Samples.UWP.csproj, Samples/Caboodle.Samples/View/PhoneDialerPage.xaml, Samples/Caboodle.Samples/View/PhoneDialerPage.xaml.cs, Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs, Samples/Caboodle.Samples/ViewModel/PhoneDialerViewModel.cs, docs/en/Microsoft.Caboodle/PhoneDialer.xml, docs/en/index.xml
Added the API to open the phone dialer.
- Related to issue #25
- Old PR #37 
```csharp
static class PhoneDialer {
static void Open(string number);
}
```
Added the PhoneDialer API.
=> GH-25: Add PhoneDialer API

DeviceTests/build.cake
One drawback to a shared test project is that the namespace and class names aren’t descriptive of the platform they are running on.  When merging all the test results in CI systems, we lose the ability to easily identify where a test case was ran (especially if it failed).
This will quickly replace some text in the test results file to be specific about the platform each test was run on.
=> Make Device Test results specify platform in names

Caboodle/Battery/Battery.android.cs, Caboodle/Caboodle.csproj, Caboodle/Connectivity/Connectivity.android.cs, Caboodle/Permissions/PermissionEnums.shared.cs, Caboodle/Permissions/Permissions.android.cs, Caboodle/Permissions/Permissions.ios.cs, Caboodle/Permissions/Permissions.netstandard.cs, Caboodle/Permissions/Permissions.shared.cs, Caboodle/Permissions/Permissions.uwp.cs, Caboodle/Platform/Platform.android.cs, Caboodle/Platform/Platform.ios.cs, Caboodle/Types/Shared/Exceptions.shared.cs, DeviceTests/Caboodle.DeviceTests.Android/MainActivity.cs, DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems, DeviceTests/Caboodle.DeviceTests.Shared/Permissions_Tests.cs, README.md, Samples/Caboodle.Samples.Android/MainActivity.cs
Some API's require checking permissions.  This adds some (currently) internal API's for checking permissions and requesting them.
Currently this only supports permission types which we need for other API's (`Battery`, `NetworkAccess1, and `LocationWhileInUse`).  We can add more types as we encounter the need for them.
Added: 
```csharp
internal static class Permissions {
// Throws a relevant PermissionException if permissions aren't declared in:
//   AndroidManifest.xml / Info.plist / AppxManifest.xml
internal static Task EnsureDeclaredAsync(PermissionType permission);
// Checks the permission status
internal static Task<PermissionStatus> CheckStatusAsync(PermissionType permission);
// Requests permission
internal static …
```
=> GH-18: Permissions Internal implementation

Caboodle/Caboodle.csproj, Caboodle/Vibration/Vibration.android.cs
Match Xamarin.Forms for Android NuGet Libraries.
Can no longer use fancy Android 8 Features, so if def them for now.
- Related to issue #145 
Changed:
- Vibrate will always fall back to classic.
=> GH-145 Adjust Package References for Android

Caboodle.Tests/Compass_Tests.cs, Caboodle/Compass/Compass.android.cs, Caboodle/Compass/Compass.ios.cs, Caboodle/Compass/Compass.netstandard.cs, Caboodle/Compass/Compass.shared.cs, Caboodle/Compass/Compass.uwp.cs, DeviceTests/Caboodle.DeviceTests.Shared/Compass_Tests.cs, Samples/Caboodle.Samples/ViewModel/CompassViewModel.cs, docs/en/Microsoft.Caboodle/Compass.xml, docs/en/Microsoft.Caboodle/CompassChangedEventArgs.xml, docs/en/Microsoft.Caboodle/CompassChangedEventHandler.xml, docs/en/index.xml
Makes API for compass event based.
- Related to issue #143
=> GH-143 Change compass to event based.

Caboodle/Permissions/Permissions.uwp.cs, Caboodle/Preferences/Preferences.android.cs, DeviceTests/Caboodle.DeviceTests.Android/Caboodle.DeviceTests.Android.csproj, DeviceTests/Caboodle.DeviceTests.Android/MainActivity.cs, DeviceTests/Caboodle.DeviceTests.UWP/App.xaml.cs, DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP.csproj, DeviceTests/Caboodle.DeviceTests.iOS/AppDelegate.cs, DeviceTests/Caboodle.DeviceTests.iOS/Caboodle.DeviceTests.iOS.csproj, DeviceTests/build.cake
As part of the device test runner CI scripts, run UWP
=> Run Device Tests for UWP

Caboodle/Compass/Compass.uwp.cs, DeviceTests/Caboodle.DeviceTests.Shared/Clipboard_Tests.cs, DeviceTests/Caboodle.DeviceTests.Shared/Compass_Tests.cs, DeviceTests/Caboodle.DeviceTests.Shared/Flashlight_Tests.cs, DeviceTests/Caboodle.DeviceTests.Shared/Permissions_Tests.cs, DeviceTests/Caboodle.DeviceTests.UWP/Package.appxmanifest
- Related to issue #150
None
No longer run certain tests on UWP due to permissions.
Check for null sensor on windows.
Run certain tests on ui thread for UWP.
=> GH-150 Fix tests for UWP on compass, flashlight, clipboard, and permissions!

Xamarin.Essentials/Accelerometer/Accelerometer.ios.cs, Xamarin.Essentials/Gyroscope/Gyroscope.ios.cs, Xamarin.Essentials/Magnetometer/Magnetometer.ios.cs, Xamarin.Essentials/Platform/Platform.ios.cs
via:  https://stackoverflow.com/questions/33642590/nsoperationqueue-currentqueue-not-working
If the current queue is null because it is being called from an outside context then create a new one :)
- Related to issue #156
=> GH-156 Create new queue if null queue

Xamarin.Essentials/mdoc.targets, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/frameworks.xml
Changed the monikers per OPS documentation here: https://opsdocs.azurewebsites.net/en-us/opsdocs/partnerdocs/versions-monikers?branch=master
n/a
none
No behavioral change, only changed the names of some docs-related artifacts
=> changed mdoc frameworks to match OPS monikers

.editorconfig, DeviceTests/DeviceTests.Shared/FileSystem_Tests.cs, DeviceTests/DeviceTests.Shared/Traits.cs, Xamarin.Essentials/Connectivity/Connectivity.ios.reachability.cs, Xamarin.Essentials/DataTransfer/DataTransfer.ios.cs, Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs, Xamarin.Essentials/Geolocation/Geolocation.android.cs, Xamarin.Essentials/Geolocation/Geolocation.ios.cs, Xamarin.Essentials/Permissions/Permissions.android.cs, Xamarin.Essentials/Permissions/Permissions.shared.enums.cs, Xamarin.Essentials/Permissions/Permissions.uwp.cs, Xamarin.Essentials/Types/Shared/PreserveAttribute.shared.cs
Removed default accessibility, no `private` modifiers for members, and no `internal` modifiers for global.
Also, moved a few classes out of the nest and into the globe.
- None.
None.
None.
=> Remove Default Accessibility Modifiers

Xamarin.Essentials/SecureStorage/SecureStorage.android.cs
Seeing some older devices have issues with `GCMParameterSpec` not being supported in older BouncyCastle library versions.  We are hitting the exception here: https://github.com/bcgit/bc-java/blob/r1rv49/prov/src/main/java/org/bouncycastle/jcajce/provider/symmetric/util/BaseBlockCipher.java#L533
If you look at the code, it's clear that `GCMParameterSpec` is not recognized as a valid parameter type yet in that commit, however newer commits of this library do recognize it.
It seems like switching to `IvParameterSpec` should be harmless and make this work on older implementations.  It looks like the only difference is the ability to specify the GCM Tag size, but we are using the default 128 size anyway.
Fixes some issues on older android devices with Secure Storage
=> [SecureStorage] Use IvParameterSpec instead of GCM

Xamarin.Essentials/Connectivity/Connectivity.ios.cs, Xamarin.Essentials/Connectivity/Connectivity.ios.reachability.cs
I split the implementation into two parts:
1. static "get current state" which will create (and dispose) a new `NetworkReachability` each request in order to obtain the current state of connectivity
2. an instance "listener" which creates two `NetworkReachability` instances and these only live as long as there are handlers attached to the `Connectivity.ConnectivityChanged` event.
_NOTE: this may be helpful when reviewing due to the amount of changes to the file (GitHub tries to match everything): [refactor-ios-reachability/.../Connectivity.ios.reachability.cs](https://github.com/mattleibow/Caboodle/blob/refactor-ios-reachability/Xamarin.Essentials/Connectivity/Connectivity.ios.reachability.cs)_
- Related to issue #179 and #134 
None.
No visible changes.
=> GH-179: Refactored the iOS Reachability

build.ps1
Restore and build cannot be invoked at the same time. Restore must be done with a switch.
Fixes incorrect msbuild usage.
See this issue: https://github.com/dotnet/sdk/issues/2170
Added: 
Changed:
=> Fix restore / build issue

Samples/Samples/ViewModel/FlashlightViewModel.cs, Xamarin.Essentials/Flashlight/Flashlight.android.cs
Don't turn off flashlight if not on on dissappearing. (permission prompt).
Also refactor a bit of code.
- Related to issue #205
None
Don't prompt for permission if not supported. Throw first.
=> GH-205: Fix for flashlight toggling off when permission was prompted.

DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs, Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs
Default iOS to AfterFirstUnlockThisDeviceOnly for the cross-platform API, but allow custom platform specific methods to pass in the SecAccessible
- Related to issue #221
Added: 
-  Task<string> GetAsync(string key, SecAccessible accessible)
- Task SetAsync(string key, string value, SecAccessible accessible)
Nothing for iOS as this was the default before and what should be exposed.
=> GH-221: Add iOS SecAccessible properties

Xamarin.Essentials/Browser/Browser.android.cs, Xamarin.Essentials/Email/Email.ios.cs, Xamarin.Essentials/Email/Email.shared.cs, Xamarin.Essentials/SecureStorage/SecureStorage.android.cs, Xamarin.Essentials/TextToSpeech/TextToSpeech.android.cs
A few fixes for the release.
None.
Bug fixes.
=> A few fixes for the release.

Xamarin.Essentials/Email/Email.shared.cs
Set the `EmailMessage` properties when using the constructor.
- Related to issue #229
No public changes.
Fixed a bug.
=> GH-229: Make sure to set the email properties

docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Locale.xml, docs/en/Xamarin.Essentials/SecureStorage.xml
Just updating the docs.
None.
None.
None.
=> Update the docs with the latest APIs

Samples/Samples/Samples.csproj, Samples/Samples/View/AllSensorsPage.xaml, Samples/Samples/View/OrientationSensorPage.xaml, Samples/Samples/View/OrientationSensorPage.xaml.cs, Samples/Samples/ViewModel/HomeViewModel.cs, Samples/Samples/ViewModel/OrientationSensorViewModel.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.android.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.ios.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.netstandard.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.shared.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.uwp.cs, Xamarin.Essentials/Xamarin.Essentials.csproj
Add Orientation Sensor to API (rationale and description in issue #245)
```
public static class OrientationSensor
{
public static event OrientationSensorChangedEventHandler ReadingChanged;
public static bool IsMonitoring { get; private set; }
public static void Start(SensorSpeed sensorSpeed);
public static void Stop();
}
public delegate void OrientationSensorChangedEventHandler(OrientationSensorChangedEventArgs e);
public class OrientationSensorChangedEventArgs : EventArgs
{
public OrientationSensorData Reading { get; }
}
public struct OrientationSensorData
{
public System.Numerics.Quaternion Orientation { get; }
}
```
=> GH-245: Add Orientation Sensor

DeviceTests/DeviceTests.Shared/Preferences_Tests.cs, Xamarin.Essentials/Preferences/Preferences.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Preferences.xml
Added overloads to get and set `DateTime` values. The backing field is just a `long`, obtained from`DateTime.ToBinary`
- Related to issue #192
```csharp
public static partial class Preferences
{
public static DateTime Get(string key, DateTime defaultValue);
public static void Set(string key, DateTime value);
public static DateTime Get(string key, DateTime defaultValue, string sharedName);
public static void Set(string key, DateTime value, string sharedName);
}
```
None.
=> GH-192: Added DateTime to Preferences

DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj, DeviceTests/build.cake, Xamarin.Essentials/Xamarin.Essentials.csproj
Fixing the NuGet link to the repo, and adding the "System.Numerics.Vectors" NuGet as a dependency for all platforms.
- Related to issue #258 and #255 
None.
The "System.Numerics.Vectors" NuGet is now always installed.
=> Fixes #258 and Fixes #255

Xamarin.Essentials/Geolocation/Geolocation.android.cs, Xamarin.Essentials/Geolocation/Geolocation.ios.cs, Xamarin.Essentials/Geolocation/Geolocation.uwp.cs, Xamarin.Essentials/Types/LocationExtensions.uwp.cs
Check for null :)
- Related to issue #272
Changed:
Ensure on each platform that null is checked.
Added helpers on UWP to simplify things.
=> GH-272 Fix Null Exception on Location Updates

Xamarin.Essentials/Compass/Compass.ios.cs, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/Xamarin.Essentials/Compass.xml
Added new ShouldDisplayHeadingCalibration for iOS and setup the listener for IOS on compass
- Related to issue #281
Added: 
- bool - bool Compass.ShouldDisplayHeadingCalibration { get; set; } 
Now defaults to not showing calibration screen.
=> Fixes #181 Allowing setting of calibration for heading.

Xamarin.Essentials/Platform/Platform.uwp.cs
Fix the logic that determines whether or not on the UI thread.
None.
None.
Previously, the check was `CoreApplication.MainView.CoreWindow.Dispatcher == null` for background threads, but this is incorrect. The window will always have a thread since it was created on a thread at some point. To check if the thread is the UI thread (or if the current thread is the same as the thread as the window), use the [`HasThreadAccess` property](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.hasthreadaccess).
=> Properly check for thread access on UWP

Xamarin.Essentials/Types/Location.shared.cs
I've simply changed the order of the parameters in the call of the CalculateDistance(…).
Now the CalculateDistance(Location locationStart, Location locationEnd, DistanceUnits units) returns correct values.
- Related to issue #306
None
None
=> Fix parameters order bug on Location. CalculateDistance() call.

Xamarin.Essentials/Platform/Platform.android.cs
Fixes up handling activity changes. Helpful in fragments and sets activity right away.
- Related to issue #309 & #289 
None
=> GH-309: Fixes #309, update to set activity on init and oncreate, never null.

DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs, Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs
Android and UWP return `null` from `SecureStorage.GetAsync(..)` where the `key` is for a record that doesn't exist.  iOS was returning `string.Empty`, and this makes iOS consistent with the other platforms.
- #316 
None
`SecureStorage.GetAsync("SOME_KEY_THAT_DOESNT_EXIST")` now returns `null` on iOS.
=> [Secure-Storage] Return null everywhere for key with no value

Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs
On iOS in KeyChain, we were querying for existing records matching the expected `Account` and `Service` (good), but also the `Label` (questionably ok), and the `Accessible` (bad).
What happened was, in v0.6.0 we never set the `Accessible` property, and when an app was upgraded to v0.7.0.17 where we started setting that value, we also started looking up existing records having the new default `Accessible` value, however the record didn’t match, even though one existed with the given key, and a runtime error occurred.
Upon further investigation it looks like `Service` and `Account` are the true ‘unique’ identifying values for a given `SecRecord`, and so those are the only fields we should be using when querying for existing records.
This change removes the other fields from the existing …
=> [secure-storage] iOS: broaden record query

Xamarin.Essentials/MainThread/MainThread.uwp.cs
Fix the logic that determines whether or not on the UI thread.
None.
None.
Previously, the check was `CoreApplication.MainView.CoreWindow.Dispatcher == null` for background threads, but this is incorrect. The window will always have a thread since it was created on a thread at some point. To check if the thread is the UI thread (or if the current thread is the same as the thread as the window), use the [`HasThreadAccess` property](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.hasthreadaccess).
=>   Properly check for thread access on UWP

DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs, Samples/Samples/View/SecureStoragePage.xaml, Samples/Samples/ViewModel/SecureStorageViewModel.cs, Xamarin.Essentials/SecureStorage/SecureStorage.android.cs, Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs, Xamarin.Essentials/SecureStorage/SecureStorage.netstandard.cs, Xamarin.Essentials/SecureStorage/SecureStorage.shared.cs, Xamarin.Essentials/SecureStorage/SecureStorage.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/SecureStorage.xml
Adds `Remove(string key)` and `RemoveAll()`API's to SecureStorage.
Also removes `GetAsync(string key, SecAccessible accessible)` from iOS as we no longer use `SecAccessible` it to query for existing records, so this overload is unnecessary.
- #304 
Added: 
- `bool SecureStorage.Remove(string key);`
- `void SecureStorage.RemoveAll();`
Removed:
- `Task<string> GetAsync(string key, SecAccessible accessible);`
=> GH-304: Added `Remove` and `RemoveAll` methods to SecureStorage

Samples/Samples/View/CompassPage.xaml, Samples/Samples/ViewModel/CompassViewModel.cs, Xamarin.Essentials/Compass/Compass.android.cs, Xamarin.Essentials/Compass/Compass.shared.cs, Xamarin.Essentials/Compass/LowPassFilter.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Compass.xml
Compass api extended by  ApplyLowPassFilter property. Internally it uses a moving average filter. No unit tests were added, as there were no Platform specific unit tests.
None
- Related to issue #337 
Added: 
- bool - Compass.ApplyLowPassFilter { get; set; } 
Changed:
None
Low pass filter is initially disabled by default. @Redth suggested applying it by default, but this would be a behavioural change
=> GH-337 Android Low Pass Filter

DeviceTests/build.cake, Tests/Browser_Tests.cs, Xamarin.Essentials/Browser/Browser.android.cs, Xamarin.Essentials/Browser/Browser.ios.cs, Xamarin.Essentials/Browser/Browser.shared.cs
Previously we were passing the the url as is to each platform and letting it deal with how to parse into the platform specific url.
This handles unicode domain names (IDN Mapping aka PunyCode) for the domain, but also reconstructs the url based on the parsed System.Uri from the original string, and so the PathAndQuery will be the % escaped version which will account for unicode characters in it as well.
Finally, on iOS and Android we are using AbsoluteUri to end up with the fully IDN mapped and % encoded URL to pass to the system URL types.
- Related to issue #368
None
Describe any non-bug related behavioral changes that may change how users app …
=> GH-368: Allow for unicode in host names and escape query

DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs, Xamarin.Essentials/DeviceInfo/DeviceInfo.ios.cs, Xamarin.Essentials/Platform/Platform.ios.cs
via:
https://github.com/xamarin/xamarin-macios/blob/bc492585d137d8c3d3a2ffc827db3cdaae3cc869/tests/linker/ios/link%20sdk/LinkSdkRegressionTest.cs#L603-L631
Added tests
- Related to issue #366
None
Instead of just returning iPhone/iPad will return model number such as iPad6,3
=> Update iOS DeviceInfo.Model to return specific hw.machine 

Xamarin.Essentials/Vibration/Vibration.android.cs
Build was broken due to a change with the preprocessor directive excluding a part of the if statement.
=> Fix build error due to preprocessor directive

Xamarin.Essentials/Accelerometer/Accelerometer.android.cs, Xamarin.Essentials/Accelerometer/Accelerometer.ios.cs, Xamarin.Essentials/Accelerometer/Accelerometer.uwp.cs, Xamarin.Essentials/Compass/Compass.android.cs, Xamarin.Essentials/Compass/Compass.uwp.cs, Xamarin.Essentials/Gyroscope/Gyroscope.android.cs, Xamarin.Essentials/Gyroscope/Gyroscope.ios.cs, Xamarin.Essentials/Gyroscope/Gyroscope.uwp.cs, Xamarin.Essentials/Magnetometer/Magnetometer.android.cs, Xamarin.Essentials/Magnetometer/Magnetometer.ios.cs, Xamarin.Essentials/Magnetometer/Magnetometer.uwp.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.android.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.ios.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.uwp.cs, Xamarin.Essentials/Types/SensorSpeed.android.cs, Xamarin.Essentials/Types/SensorSpeed.ios.cs, Xamarin.Essentials/Types/SensorSpeed.uwp.cs
Restore the default report interval to release resources while the sensor is not in use
=> Sync Sensor Speeds & Reset UWP to 0

Tests/Browser_Tests.cs, Xamarin.Essentials/Browser/Browser.shared.cs
Make sure we use Authority. Via: https://stackoverflow.com/questions/2142910/whats-the-difference-between-uri-host-and-uri-authority
Authority = Host Name + Port No
And if URL protocol is using a default port, say port 80 for http URL, then only in that case Authority = Host Name (Port No is assumed to be 80),
Whereas Host Name is either Domain Name or I.P Address
Example:
http://www.example.com/ 
Authority = www.example.com
Host Name = www.example.com
http://255.255.255.255:8080/
Authority = 255.255.255.255:8080
Host Name = 255.255.255.255
- Related to issue #450
=> GH-450 Browser - Fix for authority to make sure we get the port.

Samples/Samples/View/DeviceInfoPage.xaml, Samples/Samples/ViewModel/DeviceInfoViewModel.cs, Tests/Utils_Tests.cs, Xamarin.Essentials/Types/Shared/Utils.shared.cs
=> GH-491: Fix version parsing

DeviceTests/DeviceTests.Shared/Permissions_Tests.cs, Xamarin.Essentials/Permissions/Permissions.shared.cs
Before prompting for permission we should check for mainthread and throw an exception.
- Related to issue #373 
Would possibly hang or crash the app :( now will throw exception which is documented.
=> GH-373: Permissions Must Be Invoked on MainThread else Throw Exception

Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs
The argument validation is being done under `SecureStorage.shared.cs` [here](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/SecureStorage/SecureStorage.shared.cs#L13) and [here](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/SecureStorage/SecureStorage.shared.cs#L21). There no need to repeat it in `SecureStorage.ios.cs`
=> Removed duplicated/unnecessary argument validation.

Xamarin.Essentials/AppInfo/AppInfo.ios.cs
Fixes the case when a key does not exist in the Info.plist, but still tries to convert it to a string.
- Related to issue ##523
None.
No exception.
=> GH-523: Handle the case when a key does not exist in the iOS Info.plist

Samples/Samples/ViewModel/BarometerViewModel.cs
If barometer was not supported when navigating back from the Barometer page in the Samples app, FeatureNotSupportedException was thrown and navigation was not possible.
=> Catch FeatureNotSupportedException when navigating back for Barometer

Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs
- Related to issue #561
Secure storage in iOS won't throw exception when removing key that doesn't exist
=> [Secure storage] iOS don't throw exception when removing key that doesn't exist

DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj, DeviceTests/DeviceTests.Shared/Clipboard_Tests.cs, DeviceTests/DeviceTests.Shared/DeviceTests.Shared.csproj, DeviceTests/DeviceTests.UWP/DeviceTests.UWP.csproj, DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj, Samples/Samples.Android/Samples.Android.csproj, Samples/Samples.UWP/Samples.UWP.csproj, Samples/Samples.iOS/Samples.iOS.csproj, Samples/Samples/Samples.csproj, Samples/Samples/ViewModel/ClipboardViewModel.cs, Tests/Clipboard_Tests.cs, Tests/Tests.csproj, Xamarin.Essentials/Clipboard/Clipboard.android.cs, Xamarin.Essentials/Clipboard/Clipboard.ios.cs, Xamarin.Essentials/Clipboard/Clipboard.netstandard.cs, Xamarin.Essentials/Clipboard/Clipboard.shared.cs, Xamarin.Essentials/Clipboard/Clipboard.uwp.cs, Xamarin.Essentials/Xamarin.Essentials.csproj, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Clipboard.xml
Fix Clipboard API.
- Related to issue #569 
Changed:
- void Clipboard.SetText(string) -> Task Clipboard.SetTextAsync(string)
=> GH-569: Fixed up Clipboard API! Updated everything SetTextAsync.

DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs, Xamarin.Essentials/SecureStorage/SecureStorage.android.cs
Need to properly handle issues when key can't be unwrapped.
- Related to issue #564 
If the key can not be unwrapped then tear down the entire secure storage stack. This needs to be documented. It should not happen ideally ever.
=> GH-564 Handle Key Unwrap Exception

Xamarin.Essentials/MainThread/MainThread.uwp.cs
If there is no main window, then there is no UI thread.
Closes #510
=> GH-510: If there is no main window, then there is no UI thread

Xamarin.Essentials/PhoneDialer/PhoneDialer.ios.cs
We shouldn't have a need for telephony as we don't check it on others and restricts VOIP apps.
- Related to issue #612
If no sim and just wifi will work (iPad)
=> GH-612: Remove iOS Dependency on telephony

Samples/Samples.Android/Samples.Android.csproj, Samples/Samples/View/EmailPage.xaml, Samples/Samples/ViewModel/EmailViewModel.cs
Related to #620, just adds a way to test it.
=> GH-620: Integrate html option into sample for email.

Xamarin.Essentials/Permissions/Permissions.android.cs, Xamarin.Essentials/Permissions/Permissions.ios.cs, Xamarin.Essentials/Permissions/Permissions.shared.cs, Xamarin.Essentials/Permissions/Permissions.uwp.cs
UWP needs it all the time :(
- Related to issue #621
Added: 
Changed:
=> GH-621: Ensure we only check is main thread when prompting 

Xamarin.Essentials/Preferences/Preferences.android.cs
- Related to issue #636
Changes Android's Preference implementation of `PlatformRemove` and `PlatformClear` to be performed asynchronously.
`Preferences.Remove` and `Preferences.Clear` will write to disk asynchronously.
=> Use SharedPreferences.Editor.Apply to perform disk writes asynchronously 

DeviceTests/DeviceTests.Shared/Connectivity_Tests.cs, Xamarin.Essentials/Connectivity/Connectivity.shared.cs
Return only distinct profiles.
- Related to issue #649
Used to be able to return multiple of the same connectivity profile. Now only distinct.
=> GH-649: Return distinct connectivity profiles.

Xamarin.Essentials/Connectivity/Connectivity.android.cs
Always check IsAvailable
This may fix #656 on select phones where wifi is returned even though it isn't available.
Still need to investigate profiles
On select devices a network may be returned even in airplane mode, but will be marked as not available. 
- Related to issue #656
Added: 
Changed:
=> GH-656: Connectivity Updates on Android for Not Available

Xamarin.Essentials/Geolocation/Geolocation.ios.cs
Even though macOS is not yet officially supported, it is nice to reuse this code. macOS is exactly the same, except for this single property not supported.
https://developer.apple.com/documentation/corelocation/cllocationmanager/1620553-pauseslocationupdatesautomatical
None.
None for iOS.
> VS bug [#756378](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/756378)
=> Allow for code reuse on macOS

Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs
Need to return known and calculate tablet vs phone as "Normal" is returned by all standard devices.
- Related to issue #668 
Added: 
Changed:
```csharp
}
```
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version …
=> GH-668 Calculate Phone v Tablet on Android correctly

Xamarin.Essentials/Browser/Browser.android.cs, Xamarin.Essentials/Browser/Browser.ios.cs, Xamarin.Essentials/Browser/Browser.netstandard.cs, Xamarin.Essentials/Browser/Browser.shared.cs, Xamarin.Essentials/Browser/Browser.uwp.cs, Xamarin.Essentials/Types/PlatformExtensions/ColorExtensions.shared.cs, Xamarin.Essentials/Xamarin.Essentials.csproj
Implemented some Features required for GH- #196. 
Added: 
```csharp
public readonly struct EssentialsColor : IEquatable<EssentialsColor>
{
public byte R { get; }
public byte G { get; }
public byte B { get; }
public byte A { get; }
}
public readonly partial struct BrowserLaunchOptions : IEquatable<BrowserLaunchOptions>
{
public EssentialsColor? PreferredTitleColor { get; }
public EssentialsColor? PreferredBackgroundColor { get; }
public EssentialsColor? PrefferedControlColor { get; }
public bool? ShouldShowTitle { get; }
}
```
Changed:
- `Browser.OpenAsync(string uri, BrowserLaunchOptions options = default) // Added default parameter`
None. All values are nullable. If they are not set as they are by default no changes are made.
=> GH-196 Browser Customization

Tests/UnitConverters_Tests.cs, azure-pipelines.yml
Added: 
Changed:
```csharp
}
```
=> Add all possible combinations  for coords to km or mile

Xamarin.Essentials/Launcher/Launcher.android.cs, Xamarin.Essentials/Launcher/Launcher.ios.cs
- Related to issue #714
None
We don't escape these uris anyways and always wanted to use the original. The problem is that the URI adds in a / :( no way to get around it except to use the original, which is the correct thing to do.
=> GH-714 Use original string instead of Uri for ios/android

Xamarin.Essentials/Xamarin.Essentials.csproj
Context: https://github.com/dotnet/core/blob/79c19c12ab2bc11912551bb0c3025f602cd541d9/Documentation/diagnostics/portable_pdb.md
In doing some performance testing with builds in VS 2019, I noticed:
115 ms  _ConvertPdbFiles                           1 calls
And looking at files were converted:
ConvertDebuggingFiles
Parameters
Files
C:\ProgramData\Xamarin\NuGet\xamarin.essentials\1.0.1\lib\monoandroid81\Xamarin.Essentials.pdb
[Output] ConvertedFiles:
C:\ProgramData\Xamarin\NuGet\xamarin.essentials\1.0.1\lib\monoandroid81\Xamarin.Essentials.dll
The Xamarin.Essentials NuGet package is shipping a non-portable PDB
file. This is a Windows-specific format that Mono doesn't support.
Xamarin.Android runs a tool called `pdb2mdb` when it encounters a
non-portable PDB file so symbols be converted to …
=> Use "portable" PDB files

Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs, azure-pipelines.yml
Uses real device metrics instead of app.
- Related to issue #745
Will return different device metrics, but are correct to match iOS/UWP
=> Fixes #745 to return real metrics, not app metrics on display.

Xamarin.Essentials/MainThread/MainThread.uwp.cs
Additional null checks on main window if called at the start of an app.
- Related to issue #510
Added: 
Changed:
```csharp
}
```
=> Check for null MainView on UWP

DeviceTests/DeviceTests.Shared/Launcher_Tests.cs, Xamarin.Essentials/Launcher/Launcher.ios.cs
If not encoded string then NSUrl gets mad so try original first for launcher else use absolute
- Related to issue #794 
None
=> Fixes #794 try to use original string first else absolute for NSUrl

Tests/Browser_Tests.cs, Xamarin.Essentials/Browser/Browser.shared.cs
After calling `Browser.OpenAsync` with the URL that contained a fragment part, the fragment part was being omitted as a result of a call to `Browser.EscapeUri`.
Changed `Browser.EscapeUri` to include the fragment part of the escaped URL as its last part. 
[See RFC 3986](https://www.ietf.org/rfc/rfc3986.txt)
- Related to issue #808 
None
=> Fixes issue https://github.com/xamarin/Essentials/issues/808

DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj, DeviceTests/DeviceTests.Android/Resources/Resource.designer.cs, DeviceTests/DeviceTests.Shared/DeviceTests.Shared.csproj, Xamarin.Essentials.sln, Xamarin.Essentials/Vibration/Vibration.uwp.cs, Xamarin.Essentials/Xamarin.Essentials.csproj, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/Xamarin.Essentials/ColorExtensions.xml, docs/en/Xamarin.Essentials/PointExtensions.xml, docs/en/Xamarin.Essentials/RectangleExtensions.xml, docs/en/Xamarin.Essentials/SizeExtensions.xml, nuget.config
A cleanup to bring in latest SDKExtras for VS 2019 16.1.3 compat
=> Bring in latest version of sdk extras

Xamarin.Essentials/Browser/Browser.ios.cs
We were using too new of an API for openurl so <12 woudl have issues
- Related to issue #269
When using external it should be fine now on devices < 12
=> Put in check for iOS 12 to use new openurlasync method

Xamarin.Essentials/Geolocation/GeolocationRequest.shared.cs
Fixes #802
Added: 
Changed:
```csharp
}
```
=> Updated GeolocationRequest.shared.cs to correct power setting comment

Xamarin.Essentials/Share/Share.ios.cs
Very simple improvement making ShareActivityItemSource members readonly.
=> Made ShareActivityItemSource members readonly.

Samples/Samples.Tizen/Samples.Tizen.csproj, Xamarin.Essentials/Xamarin.Essentials.csproj
I fixed the reference to not include `System.Numerics.Vectors.dll` in `Sample.Tizen` project
=> [Tizen] Fix reference for avoid duplication

Xamarin.Essentials/Launcher/Launcher.ios.tvos.cs
On phones we need use the bounds and on iPad we need to specify. Usually this is based on a button or toolbar item, but we just put it in the bottom center, which looks pretty good. 
- Related to issue #833 
Added: 
Changed:
```csharp
}
```
Now work on iPad :)
=> GH-833 Fix Open File on iPad

Xamarin.Essentials/Email/Email.shared.cs, Xamarin.Essentials/Types/PlacemarkExtensions.shared.cs
Fixes #843 
Because the things we are escaping are parts of the url, not the whole uri
=> Updated to use UrlEncode in GetMailToUrl

Samples/Samples.Tizen/Program.cs, Samples/Samples.Tizen/Samples.Tizen.csproj
Removed a reference on Samples.Tizen project.
The Tizen.Wearable.CircularUI pacakge was used for the appearance of components on the Tizen watch device, it is not a mandatory package.
Besides it may causes a conflict with the Xamarin.Forms package depending on the version.
So this Tizen.Wearable.CircularUI pacakge reference should be removed.
=> [Tizen] Removed non-mandatory reference

Xamarin.Essentials/Xamarin.Essentials.csproj
The only class that is part of *Xamarin.Android.Support.Core.Utils* in Monodroid90 is an obsolete BroadcastReceiver which Essentials doesn't use
The types used by early Monodroid versions looks to have been moved to the Compat library
This will simplify the transient dependencies for MonoAndroid 9.0 and up
This shouldn't change anything
=> Xamarin.Android.Support.Core.Utils isn't needed for Monodroid90 and up

Xamarin.Essentials/PhoneDialer/PhoneDialer.android.cs
URL encoding the phone number to ensure that extension dialing works fine.
Added code to encode the phone number, before being passed to the dialer. This makes it possible for the dialer to understand the pause needed for dialing an extension e.g. "+1 555 010 9999, 222" where "222" is an extension number
- Related to issue #912
None
None
Existing tests, documentation and samples do not need to change.
=> URL Encode Phone Number on Android intent (Fixes #912)

build.ps1
This error was happening when trying to build XamarinEssentials
under a GithubActions VM:
```
Run .\build.ps1
Using MSBuild from: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
& : The term 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\a\DotNetEssentials\DotNetEssentials\build.ps1:27 char:3
+ & $msbuild "./Xamarin.Essentials.sln" /restore /t:Build /p:Configurat ...
+   ~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Program Files (x\u20265.0\Bin\MSBuild.exe:String) [], …
```
=> build.ps1: fix build with GithubActionsCI

docs/en/Xamarin.Essentials/EmailAttachment.xml, docs/en/Xamarin.Essentials/FileBase.xml, docs/en/Xamarin.Essentials/ReadOnlyFile.xml
From feedback at https://github.com/MicrosoftDocs/xamarin-docs/issues/2246
Improving the API docs to be more clear that Content Type is MIME type.
=> Clarify ContentType API

CONTRIBUTING.md
Can't have a relative path to the wiki here
=> Fix broken docs link

Xamarin.Essentials/mdoc.targets
Fix reference assemblies for mdoc on  windows so we can run `/t:MDocUpdateDocs`
=> Fix path to reference assemblies on win for mdoc

Samples/Samples/ViewModel/ShareViewModel.cs, Xamarin.Essentials/Share/Share.ios.cs, Xamarin.Essentials/Share/Share.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-tvos.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials-watchos.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/ShareFileRequest.xml, docs/en/Xamarin.Essentials/ShareRequestBase.xml, docs/en/Xamarin.Essentials/ShareTextRequest.xml, docs/en/index.xml
Adds the ability to specify a Source Rectangle for Share*Requests.  This is really only used for now on iOS where on some iOS 13 versions it seems the `sourceRect` needs to be set in order for the dialog to display.
This should address #980 #979 #944 by allowing users to set their own source position.
=> Add Share Source Position

Tests/Color_Tests.cs, Xamarin.Essentials/Types/ColorConverters.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-tvos.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials-watchos.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/ColorConverters.xml
For #1012
Update the name of a method previously added in #970 
Based on [this comment](https://github.com/xamarin/Essentials/pull/970#issuecomment-563155207) it turns out I can't spell.
Updated code, tests, and docs files.
There are no samples for this method.
- Related to issue #1012 
Changed:
- `ColorExtensions.GetCompliment` => `ColorExtensions.GetComplementary`
none
=> Rename GetCompliment to GetComplementary

Samples/Samples.UWP/App.xaml.cs, Xamarin.Essentials/MainThread/MainThread.uwp.cs
Even though we check for null it is possible that this check will throw an exception :(
- Related to issue #1020
None
Com exception wont be thrown
=> GH-1020 - Fix issue with checking mainthread to early on UWP.

Xamarin.Essentials/Accelerometer/Accelerometer.shared.cs, Xamarin.Essentials/Barometer/Barometer.shared.cs, Xamarin.Essentials/Compass/Compass.shared.cs, Xamarin.Essentials/Gyroscope/Gyroscope.shared.cs, Xamarin.Essentials/Magnetometer/Magnetometer.shared.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.shared.cs, Xamarin.Essentials/Types/DeviceIdiom.shared.cs, Xamarin.Essentials/Types/DevicePlatform.shared.cs, Xamarin.Essentials/Types/DisplayInfo.shared.cs
Fix boxing on structs
- Related to issue #1004
Added: 
Changed:
```csharp
}
```
=> GH-1004 Cleanup equals in IEquatable so no boxing occurs.

Xamarin.Essentials/OrientationSensor/OrientationSensor.ios.watchos.cs
* this is a fix-up for commit 84579595f36a008e172824aa41269596d83d167c
* quaternions are not commutative, and the original commit had the multiplication in the wrong order
* it worked for some special cases, but not in general
- Related to issue #981
None.
None.
=> bugfix for OrientationSensor on iOS

Xamarin.Essentials/Permissions/Permissions.ios.tvos.watchos.cs
Must cache location manager: https://stackoverflow.com/questions/7888896/current-location-permission-dialog-disappears-too-quickly/8170382
Clean it up when doen. 
- Related to issue #1066
None
Else dialog disappears :(
=> Fixes #1066 Need to cache locationmanager or dialog dissapears

Xamarin.Essentials/Battery/Battery.shared.cs
This double is not in the interning list of doubles(infinity, neg infinity,+0, -0 etc.), so this will allocate less. Verified in Benchmark.Net for random doubles assigned from int values 1-100
=> Tiny allocation optimization

Xamarin.Essentials/DeviceInfo/DeviceInfo.uwp.cs
An exception may occurs (perhaps backgrounding), so cache it as it never is going to change.
- Related to issue #1014
May return unknown if it can't figure it out if an exception is thrown
=> GH-1014 Try to cache device type on UWP

Samples/Samples/ViewModel/GeolocationViewModel.cs, Xamarin.Essentials/Types/Location.shared.cs, Xamarin.Essentials/Types/LocationExtensions.android.cs, Xamarin.Essentials/Types/LocationExtensions.ios.tvos.watchos.cs, Xamarin.Essentials/Types/LocationExtensions.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-tvos.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials-watchos.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/Location.xml
This extends the GeoLocation API to provide the vertical accuracy.
- Related to issue #1099
Added: 
- `double? Location.VerticalAccuracy { get; set; }`
Changed:
- None
None.
=> Implement vertical accuracy in GeoLocation API

.gitattributes
This PR simply uncomments one line in the gitattributes file, giving me better diff context in hunk headers.
Background: When looking at commit diffs (at the command line or via tools like gitk), one currently gets rather bad context indicators in the hunk headers for C# code (usually the enclosing namespace). With this change, the situation improves a lot, and one gets the correct context (class or function name). Not sure why this is commented out in the first place.
=> .gitattributes: get better diff context for C# code

Xamarin.Essentials/Types/LocationExtensions.android.cs
* the compile-time check is not enough
* it crashed on old Android versions (<8.0)
- Related to issue #1099 
None.
None.
=> Location.VerticalAccuracy: add runtime check for Android version

Xamarin.Essentials/Browser/Browser.ios.cs, Xamarin.Essentials/Launcher/Launcher.ios.tvos.cs
- Related to issue #1102 
Added: 
Changed:
```csharp
}
```
=> GH-1102 Fix launcher on older devices

Xamarin.Essentials/Permissions/Permissions.uwp.cs
We need to set a empty array else we get an exception
- Related to issue #1129
=> Fixes #1129 - set empty required declarations on UWP

Xamarin.Essentials/Permissions/Permissions.android.cs, Xamarin.Essentials/Platform/Platform.android.cs
- Related to issue #1142
Added Q Check and use it instead of just compile check
Now should validate background permissions too.
=> GH-1142 AccessBackgroundLocation only when compile & running Q

Xamarin.Essentials/AppInfo/AppInfo.ios.tvos.watchos.cs
VC may be null at startup so use traitcollection
- Related to issue #1121 
None.
Should now work at startup.
=> GH-1121 If VC is null use TraitCollection

Xamarin.Essentials/FilePicker/FilePicker.android.cs
This is a continuation of PR #975 where all of the commits were merged to the dev/file-picker branch. There are some compiler errors in this branch, which this PR should fix. My hope is that we can continue working on the FilePicker then and finally bring this feature to a close.
- Related to issue #975, #790, #613, #986 and #251
None.
None
=> Fix FilePicker permissions check

Samples/Samples/View/FilePickerPage.xaml, Samples/Samples/ViewModel/FilePickerViewModel.cs, Xamarin.Essentials/FilePicker/FilePicker.android.cs, Xamarin.Essentials/FilePicker/FilePicker.ios.cs, Xamarin.Essentials/FilePicker/FilePicker.netstandard.watchos.tvos.cs, Xamarin.Essentials/FilePicker/FilePicker.shared.cs, Xamarin.Essentials/FilePicker/FilePicker.tizen.cs, Xamarin.Essentials/FilePicker/FilePicker.uwp.cs
Based on PR #1137, #975 and some more PRs I implemented multiple file picking, for Android, iOS and UWP. Tizen implementation is missing at the moment. Multiple file picking works from Android 4.3 and iOS 11 on. Throws `FeatureNotSupportedException` when running on devices before that versions.
Note: The PR also contains the changes from #1137, which probably should be merged before applying this PR.
- Related to issue #1137, #975
Added: 
- ` public static Task<IEnumerable<FilePickerResult>> PickMultipleFilesAsync(PickOptions options)`
No behavioral changes.
=> FilePicker picking multiple files

Xamarin.Essentials/AppInfo/AppInfo.ios.tvos.watchos.cs, Xamarin.Essentials/Launcher/Launcher.shared.cs, Xamarin.Essentials/Permissions/Permissions.android.cs, Xamarin.Essentials/Permissions/Permissions.uwp.cs, Xamarin.Essentials/Platform/Platform.android.cs, Xamarin.Essentials/Xamarin.Essentials.csproj, docs/en/Xamarin.Essentials/PlacemarkExtensions.xml
* Implement vertical accuracy in GeoLocation API (#1103)
* Location: add property 'VerticalAccuracy' (#1099)
* vertical accuracy is only available in Android API level 26 and above (#1099)
* update Samples app to show vertical accuracy on GeolocationPage
* add missing documentation bits for Location.VerticalAccuracy
* .gitattributes: get better diff context for C# code (#1115)
* Location.VerticalAccuracy: add runtime check for Android version (#1099) (#1116)
* the compile-time check is not enough
* it crashed on old Android versions (<8.0)
* GH-1102 Fix launcher on older devices (#1120)
* Update Launcher.ios.tvos.cs
* OpenUrlAsync was introduced in iOS 10 not 12
https://docs.microsoft.com/en-us/dotnet/api/uikit.uiapplication.openurlasync?view=xamarin-ios-sdk-12
* Fix trailing whitespace
* …
=> 1.5.1 (#1145) -> Merge into develop

Xamarin.Essentials/Permissions/Permissions.ios.tvos.watchos.cs
Currently, we prompt for permission is it is disabled, but we shouldn't and just return that state.
Fixes #1161
=> Don't request location permission if disabled.

Xamarin.Essentials/Accelerometer/Accelerometer.android.cs, Xamarin.Essentials/Barometer/Barometer.android.cs, Xamarin.Essentials/Compass/Compass.android.cs, Xamarin.Essentials/Gyroscope/Gyroscope.android.cs, Xamarin.Essentials/Magnetometer/Magnetometer.android.cs, Xamarin.Essentials/OrientationSensor/OrientationSensor.android.cs
=> GH-1148 Check array length on sensors on Android

docs/en/Xamarin.Essentials/AppInfo.xml
Changed 'android' to 'Android'
=> Documentation change - tiny typo

Xamarin.Essentials/Permissions/Permissions.android.cs
This is a special permission on 18 that just needs a manifest check: https://developer.android.com/reference/android/Manifest.permission#BATTERY_STATS
Now will return granted if in manifest.
=> Fix CheckStatus for Battery Permission on Android

Xamarin.Essentials/OrientationSensor/OrientationSensor.android.cs
Builds on top of previous PR so we return -1 if 4th value isn't present.
- Related to issue #1148
Will return -1 if [3] isn't available on Android
=> GH-1148 - Check if 4th value is present in orientation sensor

Xamarin.Essentials/Launcher/Launcher.android.cs, Xamarin.Essentials/Launcher/Launcher.tizen.cs, Xamarin.Essentials/Launcher/Launcher.uwp.cs
Invoking launcher needs main thread so can't use configure await false.
- Related to issue #1158
Tested on latest targets on UWP
=> GH-1158 Remove configure await false, needs to be on main thread.

Xamarin.Essentials/Platform/Platform.android.cs
This should never ever change at runtime, so should be safe to cache.
=> Cache Android SdkInt at runtime

Samples/Samples/View/BrowserPage.xaml, Samples/Samples/ViewModel/BrowserViewModel.cs, Xamarin.Essentials/Browser/Browser.android.cs, Xamarin.Essentials/Browser/Browser.ios.cs, Xamarin.Essentials/Browser/BrowserLaunchOptions.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-tvos.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials-watchos.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/BrowserLaunchFlags.xml, docs/en/Xamarin.Essentials/BrowserLaunchOptions.xml, docs/en/Xamarin.Essentials/Permissions+Battery.xml, docs/en/index.xml
Based off feedback of launching new task for system. Can't find google docs showing to do it how we have it and my old plugin didn't have it.
- Related to issue #1180
Will now launch in same activity.
=> GH-1180 ; Don't launch new task on custom tabs.

Samples/Samples/View/WebAuthenticatorPage.xaml, Samples/Samples/ViewModel/WebAuthenticatorViewModel.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticatorResult.shared.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-tvos.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials-watchos.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/WebAuthenticatorResult.xml
Apple doesn't return an access token on iOS native sign in, but it does return id_token as a JWT.  This adds a property to the auth result to access IdToken easily and then changes the sample to try and use IdToken if AccessToken is null.
=> Add id_token property

Samples/Samples/ViewModel/GeolocationViewModel.cs, Xamarin.Essentials/Types/Location.shared.cs, Xamarin.Essentials/Types/LocationExtensions.android.cs, Xamarin.Essentials/Types/LocationExtensions.ios.tvos.watchos.cs, Xamarin.Essentials/Types/LocationExtensions.uwp.cs, docs/en/FrameworksIndex/xamarin-essentials-android.xml, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-tvos.xml, docs/en/FrameworksIndex/xamarin-essentials-uwp.xml, docs/en/FrameworksIndex/xamarin-essentials-watchos.xml, docs/en/FrameworksIndex/xamarin-essentials.xml, docs/en/Xamarin.Essentials/AltitudeReferenceSystem.xml, docs/en/Xamarin.Essentials/Location.xml
In order to deal with platform differences of Location.Altitude, this PR adds a new property Location.AltitudeReferenceSystem and a corresponding enum, which is a copy of [Windows.Devices.Geolocation.AltitudeReferenceSystem](https://docs.microsoft.com/en-us/uwp/api/windows.devices.geolocation.altitudereferencesystem).
- Related to issue #1177
Added: 
- `enum AltitudeReferenceSystem`
- `AltitudeReferenceSystem Location.AltitudeReferenceSystem { get; set; }`
Changed:
- None.
=> add new property Location.AltitudeReferenceSystem

Xamarin.Essentials/TextToSpeech/TextToSpeech.ios.tvos.watchos.cs
- Related to issue #1207 
Added: 
Changed:
```csharp
}
```
=> GH-1207 - Preserve AVSpeechSynthesizer type when linking

Xamarin.Essentials/FilePicker/FilePicker.android.cs, Xamarin.Essentials/FilePicker/FilePicker.ios.cs
This is a PR with improvements of the FilePicker implementation on the 'dev/file-picker' branch. Some of the changesets are ports from [jfversluis' FilePicker implementation](https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows).
- 0d24658 fixes Android permission handling; one user reported that using `ActionOpenDocument` and calling `TakePersistableUriPermission` fixes a permission issue on newer Android version
- 7e6237f  uses the MIME type when the file name doesn't contain a file extension yet. This is for users that determine what to do with the picked file based on the file extension and the content provider doesn't provide the filename.
- e84334d: When using multi-file picking, Android returns data in `ClipData`, except for when the user only selects one file …
=> File picker improvements

Xamarin.Essentials/Email/Email.android.cs
open email applications only when call Email.ComposeAsync(). 
related issue #1081 
ref:
https://developer.android.com/guide/components/intents-common#Email
none
open email applications only.
=> Email: Open only email apps

Xamarin.Essentials/Share/Share.ios.cs
iPadOS really wants you to set a sourcerect :( it will default to 0,0,0,0, but developers should specify a correct area to open it.
- Related to issue #1247
None
Will now open in the same place on iOS 13 as iOS 12
=> Fixes #1247 Must set SourceRect in iOS 13

docs/en/Xamarin.Essentials/Location.xml
Updated Location.Course documentation to show that GetLastKnowLocationAsync wont return a value for Course.
https://developercommunity.visualstudio.com/content/problem/1023939/xamarin-essentials-geolocation-course-is-always-nu.html
=> Updated Location.Course documentation

Xamarin.Essentials/WebAuthenticator/WebAuthenticator.uwp.cs
Fxed the bug where when the user canceled operation, an exception is thrown.
According to documentation,  `WebAuthenticationBroker.AuthenticateAsync` can return `ResponseStatus` with `WebAuthenticationStatus.UserCancel` value.
Now, if that case occours, `null` is returned instead of `Exception(r.ResponseData.ToString())`.
- Related to issue #1263 
None.
According the documentation, now the behavior is correct and `WebAuthenticator.AuthenticateAsync` returns `null` when the user canceled the operation in UWP.
=> Fixed bug #1263 (WebAuthenticator - User closes dialog box)

Xamarin.Essentials/WebAuthenticator/WebAuthenticator.ios.tvos.cs
The WebAuthenticator leaks the `ASWebAuthenticationSession` or `SFAuthenticationSession` if the login attempt is being cancelled.
Surrounds the awaited task with a `try/finally` to dispose the authentication session even for the cancelled or failed cases.
Adds no tests as this is not automatically reproducible (would require ui test)
- Related to issue #1295
None
The `was` and `sf` fields are now disposed and set to null in all cases.
=> iOS: Fixes leaks in WebAuthenticator

Samples/Sample.Server.WebAuthenticator/Startup.cs
The cert generation step seems to require access to the User Profile as per Microsoft s documentation here.
https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate-in-code
---------------------
(From the Microsoft documentation stated above)
ASP.NET and ASP.NET Core on Windows must access the certificate store even if you load a certificate from a file. 
-----------------------------------------------------------------------------------------------------------------------------
Without setting the WEBSITE_LOAD_USER_PROFILE = 1 in the Azure web app configuration, the Apple sign-in will throw an exception on the server which is not always easy to debug. The app may work perfectly well on the users test IIS Server only to fail when deployed. The exception is a File Not …
=> Add comment to Startup.cs

Samples/Sample.Server.WebAuthenticator/Controllers/MobileAuthController.cs
get the email from the Claims (not sure in what situation multiple identities would be returned, but I am taking the Claims from the first one,  then add the email to the returning Dictionary.
On the Client the user can retrieve the email with....
WebAuthenticatorResult result = await WebAuthenticator.AuthenticateAsync(authUrl, callbackUrl);
if (result.Properties.Contains("email"))
string email = Uri.UnescapeDataString(result.Properties["email"]);
Return email with auth properties.
=> Return user's email as part of the properties.

Xamarin.Essentials/WebAuthenticator/AppleSignInAuthenticator.ios.cs
Just added AuthenticationCode and State properties to the WebResult.Properties dictionary.
- Related to issue #1253
None
None
=> [Enhancement] Make AuthenticationCode and State available on WebAuthenticationResult for AppleAuthenticator

Xamarin.Essentials/TextToSpeech/TextToSpeech.ios.tvos.watchos.cs
In iOS, Speech output continues for some milliseconds and in some rare cases some seconds after the Task is Cancelled, because it attempts to finish the already speaking word. This is in contrary to the Android behaviour, where the speech stops immediately. 
Since TextToSpeech is in a Nuget package, there is no way to detect when the speech stops after it has been cancelled. It will be helpful especially when we have to do "Speech To Text" right after cancelling the ongoing TextToSpeech. Otherwise, parts of the speech output are getting fed to Speech To Text implementation. The only other solution would be to "Task.Delay" for some seconds assuming speech output would finish in that timeframe, which is kind of ugly and bad UX.
_AVSpeechBoundary.Immediate_ is passed as parameter to …
=> Audio will stop immediately when the Task is cancelled.

Xamarin.Essentials/FilePicker/FilePicker.tizen.cs, Xamarin.Essentials/Permissions/Permissions.tizen.cs
This is a fix for requesting permission in order for the file picker to work properly in Tizen.
As of Tizen 4.0 and later, media storage privilege (`http://tizen.org/privilege/mediastorage`) should be treated as user privacy privilege.
- http://tizen.org/privilege/mediastorage
- Allows the application to read and write files in media folders.
- See [here ](https://www.tizen.org/privilege)full privilege.
None
None
In tizen, FilePicker requesting the user's consent to use.
=> [Tizen] Update the FilePicker implementation

Samples/Samples/ViewModel/ClipboardViewModel.cs
This fixes crash of clipboard sample when text is null.
None
Sample app doesn't crash anymore.
=> Fix crash of clipboard sample when text is null

Xamarin.Essentials/Types/FileProvider.android.cs
Put null checks in file path provider on Essentials.
- Related to issue  Fixes #1353
Added: 
Changed:
```csharp
}
```
=> [GH-1353] - Put null checks in file path provider on Android.

Samples/Samples/View/ScreenshotPage.xaml, Samples/Samples/ViewModel/MediaPickerViewModel.cs, Samples/Samples/ViewModel/ScreenshotViewModel.cs, Xamarin.Essentials/MediaPicker/MediaPicker.android.cs, Xamarin.Essentials/MediaPicker/MediaPicker.ios.cs, Xamarin.Essentials/MediaPicker/MediaPicker.macos.cs, Xamarin.Essentials/MediaPicker/MediaPicker.netstandard.watchos.tvos.cs, Xamarin.Essentials/MediaPicker/MediaPicker.shared.cs, Xamarin.Essentials/MediaPicker/MediaPicker.tizen.cs, Xamarin.Essentials/MediaPicker/MediaPicker.uwp.cs, Xamarin.Essentials/Screenshot/Screenshot.android.cs, Xamarin.Essentials/Screenshot/Screenshot.ios.tvos.cs, Xamarin.Essentials/Screenshot/Screenshot.netstandard.tizen.watchos.macos.cs, Xamarin.Essentials/Screenshot/Screenshot.shared.cs, Xamarin.Essentials/Screenshot/Screenshot.uwp.cs
Adding an `IsSupported` property to `MediaPicker` and `Screenshot`.
I also moved the check for Android to the actual inline logic because this is a window flag that can change at any time, so rather check when using it. This is also not available when navigating, so any view setup logic will be incorrect.
Added: 
Changed:
```csharp
public static int SomeProperty { get; …
```
=> Adding an IsSupported property

DeviceTests/DeviceTests.Shared/AppActions_Tests.cs, Samples/Samples/App.xaml.cs, Tests/AppActions_Tests.cs, Xamarin.Essentials/AppActions/AppActions.android.cs, Xamarin.Essentials/AppActions/AppActions.ios.cs, Xamarin.Essentials/AppActions/AppActions.shared.cs, Xamarin.Essentials/AppActions/AppActions.uwp.cs
- Tweak the AppAction param order
- Also fix the build error
Added: 
Changed:
```csharp
}
```
=> Correct the AppAction param order

Samples/Samples.Android/MainActivity.cs, Samples/Samples.Mac/AppDelegate.cs, Samples/Samples.Tizen/Program.cs, Samples/Samples.UWP/MainPage.xaml.cs, Samples/Samples.iOS/AppDelegate.cs
Stop recreating the app instance if the xamarin app's runtime is still active.
=> Make forms app static

Xamarin.Essentials/WebAuthenticator/WebAuthenticator.uwp.cs
When internet is turned off and user closes the WAB dialog in uwp, FileNotFoundException is thrown.
- Related to issue #1357 
None
Like android and ios do, when dialog is closed, a TaskCanceledException is thrown.
=> FileNotFoundException thrown by Web Authenticator in UWP. Fixed #1357

DeviceTests/build.cake, Samples/Samples.iOS/Info.plist, Samples/Samples/View/ContactsPage.xaml, Samples/Samples/View/ContactsPage.xaml.cs, Xamarin.Essentials/Contacts/Contacts.ios.cs, Xamarin.Essentials/Launcher/Launcher.ios.tvos.cs, Xamarin.Essentials/Permissions/Permissions.ios.cs, docs/en/Xamarin.Essentials/Browser.xml, docs/en/Xamarin.Essentials/FileResult.xml, docs/en/Xamarin.Essentials/Screenshot.xml
There are a couple of issues related to what I believe could be do to something going out of scope and being GC'd before the native action is complete.
This PR just keeps some instances around (and attempts to clean them up when finished).
- #1376
- #1373
=> iOS Keep things in scope

Xamarin.Essentials/Xamarin.Essentials.csproj
Adds a reference to OpenTK in the macOS project which should make it through to the nuget package.
- #1383
=> Include the OpenTK reference in macOS for System.Drawing.Color

Xamarin.Essentials/Permissions/Permissions.shared.cs
Use the correct return type for `ShouldShowRationale<T>()` on the `Permissions` API.
- Related to issue #1200
`Permissions.ShouldShowRationale<TPermission>()`
=> Use the correct return for ShouldShowRationale

Samples/Samples.Mac/Samples.Mac.csproj, Xamarin.Essentials/Types/PlatformExtensions/ColorExtensions.macos.cs
Ensure colorspaces are valid
- Fixes #1383
Added: 
Changed:
```csharp
}
```
=> [macOS] Ensure colorspaces are valid

Samples/Samples.Mac/Samples.Mac.csproj, Xamarin.Essentials/Types/PlatformExtensions/ColorExtensions.macos.cs
DeviceInfo API was returning device model as a device name.
Description of Change
Describe your changes here.
Bugs Fixed
Related to issue #
#1417
API Changes
DeviceInfo
Added:
if (Essentials.Platform.HasApiLevelNMr1)
return Settings.Global.GetString(Essentials.Platform.AppContext.ContentResolver, name);
Behavioral Changes
Now user will get correct device name if device OS version is 7.1 or later
=> Fixed wrong device name issue

Xamarin.Essentials/Screenshot/Screenshot.uwp.cs
When generationg the screenshot in UWP, I made sure the execution thread remains the same, by setting `ConfigureAwait(true)`
- Related to issue #1432 
None
None
=> Ensure we use the same thread when getting a Screenshot in UWP

Samples/Samples.iOS/AppDelegate.cs, Xamarin.Essentials/Platform/Platform.ios.tvos.watchos.cs, docs/en/FrameworksIndex/xamarin-essentials-ios.xml, docs/en/FrameworksIndex/xamarin-essentials-tvos.xml, docs/en/Xamarin.Essentials/Platform.xml, docs/en/index.xml
This addresses an issue raised in https://github.com/MicrosoftDocs/xamarin-docs/issues/2716
Universal App Links in iOS can callback to the `AppDelegate.ContinueUserActivity` method instead of the OpenUrl.  If you were using Universal App Links on iOS to implement the callback handler for the Authentication API, your app would never see the callback while waiting.
This adds a `Xamarin.Essentials.Platform.ContinueUserActivity` implementation to pass through from the AppDelegate which will in turn call the the `WebAuthenticator.OpenUrl` method and complete the waiting task with the app links callback.
- Related to issue #1456 
- Related to https://github.com/MicrosoftDocs/xamarin-docs/issues/2716
Provide links to issues here. Ensure that a GitHub issue was created for your feature or bug fix …
=> Add ContinueUserActivity impl for Universal App Links

Xamarin.Essentials/Platform/Platform.android.cs
Make sure that there is always a valid Intent when the intermediate activity returns.
- Fixes #1397
None.
If the intent is null, then create one and not crash.
=> Make sure that there is always a valid Intent

docs/en/docfx.json
Turn off the feedback control for API docs.
There's currently no way of turning off page feedback and leaving the product feedback button in place. However, in case DCM ever supports this I've left the product feedback config in place.
=> Turn off feedback control for ref docs.

Xamarin.Essentials/Permissions/Permissions.ios.tvos.watchos.cs, Xamarin.Essentials/Types/LocationExtensions.ios.tvos.watchos.macos.cs
Adapts code to new CLLocationManager APIs in iOS 14 (tvOS 14, watchOS 7) while keeping existing logic for older versions.
- Fixes #1390 
None
None
=> Handle new iOS location permission event (issue 1390)

Xamarin.Essentials/TextToSpeech/TextToSpeech.macos.cs
`hWord` is obsolete, replaced it with `Word`
- Related to issue #1429
=> macOS: TextToSpeech replaced NSSpeechBoundary

Xamarin.Essentials/TextToSpeech/TextToSpeech.macos.cs
Reverts xamarin/Essentials#1430
=> Revert "macOS: TextToSpeech replaced NSSpeechBoundary"

Samples/Samples/View/ClipboardPage.xaml, Samples/Samples/ViewModel/ClipboardViewModel.cs, Xamarin.Essentials/Clipboard/Clipboard.android.cs, Xamarin.Essentials/Clipboard/Clipboard.ios.cs, Xamarin.Essentials/Clipboard/Clipboard.macos.cs
- Fixes #1321 
Added: 
Changed:
```csharp
}
```
=> Add sample for hastext on clip & check IsNullOrEmpty

Xamarin.Essentials/FilePicker/FilePicker.ios.cs
On pre-iOS 11, the `UIDocumentPickerViewController.AllowsMultipleSelection` did not exist.
Our previous solution was to throw, but this is inconsistent with all the other platforms. If an app on android can't pick multiple files, then it still works as the multiple flag is almost optional.
- Fixes #1492
None.
On older iOS versions, the app no longer throws an exception.
=> Don't throw if iOS can't pick multiple files

DeviceTests/DeviceTests.Shared/Launcher_Tests.cs, Samples/Samples/ViewModel/WebAuthenticatorViewModel.cs, Xamarin.Essentials/Launcher/Launcher.ios.tvos.cs, Xamarin.Essentials/Launcher/Launcher.macos.cs, Xamarin.Essentials/Types/Shared/WebUtils.shared.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticator.ios.tvos.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticator.macos.cs
When using `ASWebAuthenticationSession` and `SFAuthenticationSession`, the cancellation operations are marked by iOS throwing an exception. This PR catches those errors and then converts them into cancellation exceptions.
I also removed the containing try/catch block as that was actually catching the exceptions that were set in the `TaskCompletionSource` and then re-throwing them.
- Don't catch our own errors and then throw them
- Correctly convert from cancellation NSErrors into .NET cancellation exceptions
- Fixes #1240
- Related to #1295
- Fixes #1307
None.
iOS cancellation errors are now exposed as .NET cancellation exceptions.
=> [iOS] [WebAuth] Correctly interpret iOS WebAuthenticator errors

Xamarin.Essentials/Platform/Platform.android.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticator.android.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticatorCallbackActivity.android.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticatorIntermediateActivity.android.cs, build.cake
Rework the authentication flow to better support interruptions, either by the user or the actual process of authentication via 2FA.
The new flow makes use of 2 "intermediate" activities. The first one, `WebAuthenticatorIntermediateActivity`, represents the container for the actual authentication process and starts the custom tabs. This will then handle the interruptions. The second one, `WebAuthenticatorCallbackActivity`, represents the "authenticated" path. This activity will then re-launch the first activity, but this time with different flags. These new flags will close the custom tabs and then complete the flow. 
- Fixes #1292
- Fixes #1336
- Fixes #1303
None.
None.
=> [Android] [WebAuth] Rework authentication flow

Xamarin.Essentials/MediaPicker/MediaPicker.ios.cs
Attaching a `UIAdaptivePresentationControllerDelegate` to the `picker.PresentationController.Delegate` property so we can hook into the `DidDismiss()` method and fire a cancel action when the user dismisses the picker when swiping down
- Related to issue #1493 
None
The library now returns `null` when a user dismisses the picker by swiping down.
=> [Issue-1493] iOS MediaPicker.PickPhotoAsync() never returns 

Samples/Samples.Android/Properties/AndroidManifest.xml, Samples/Samples.iOS/Info.plist, Xamarin.Essentials/Email/Email.shared.cs, Xamarin.Essentials/TextToSpeech/TextToSpeech.macos.cs
According to the spec: https://www.ietf.org/rfc/rfc2368.html#page-2
```
Also note that it is legal to specify both "to" and an "hname" whose
value is "to". That is,
mailto:addr1%2C%20addr2
is equivalent to
mailto:?to=addr1%2C%20addr2
is equivalent to
mailto:addr1?to=addr2
```
But not for Google on iOS.
- Related to issue #1401
None.
mailto URI used now has the "to" as the first part.
=> Apple does not use the "?to=xxx" version of the mailto

Xamarin.Essentials/MediaPicker/MediaPicker.ios.cs
Explicitly check and ask for permissions as since iOS 11 the UIImagePickerController normally takes care of this. This however can lead to the camera view being open while a user denies the permission and it just showing a black screen. Might be less confusing if it lets the user know that the permission was not granted so they can ask for it again. 
Divided the checks in to camera and photo separately. It could be somebody blocking access to their Photo Library but wanting to access the camera. Therefor check what action they want to perform and check the permission accordingly.
- Related to issue #1509 
None
Instead of seeing the UIImagePickerController appearing behind the alert asking for permission and potentially resulting in a black screen, it now asks for the permission before …
=> [Issue-1509] Change permission request for Photo and Camera

Samples/Samples/ViewModel/WebAuthenticatorViewModel.cs, Xamarin.Essentials/WebAuthenticator/AppleSignInAuthenticator.ios.cs
Get the correct name from the components. Previously we were retrieving the phonetic name, without first checking for it.  I am not sure we actually want to do that and we rather ant the name as it is specified.
- Fixes #1288
None.
The `name` is now correctly parsed from the sign in response.
=> Get the correct name from the components

Xamarin.Essentials/Platform/Platform.android.cs, Xamarin.Essentials/Types/FileProvider.android.cs
Even though we actually reference it directly in code to get te Uri, this is actually on the base type and thus gets resolved to the base type in IL. As a result, the code never actual references the local type and it gets linked out, the manifest does not have the element and nothing works.
- Fixes #1513
None.
No more crashes.
=> "preserve" the FileProvider by using it

Xamarin.Essentials/AppInfo/AppInfo.ios.tvos.watchos.macos.cs, Xamarin.Essentials/Browser/Browser.ios.cs, Xamarin.Essentials/Email/Email.ios.cs, Xamarin.Essentials/Launcher/Launcher.ios.tvos.cs, Xamarin.Essentials/PhoneDialer/PhoneDialer.ios.cs
Use OpenUrl with only 1 parameter only on < iOS 10 and update the rest of the code for consistentcy
- Fixes #1535
Did all checks against API 10 and above to make the right calls.
=> Ensure iOS 9 is supported on all OpenUrl calls.

Samples/Samples.Android/Properties/AndroidManifest.xml, Samples/Samples/ViewModel/ShareViewModel.cs, Tests/FileSystem_Tests.cs, Xamarin.Essentials/Email/Email.android.cs, Xamarin.Essentials/FilePicker/FilePicker.android.cs, Xamarin.Essentials/FilePicker/FilePicker.ios.cs, Xamarin.Essentials/FilePicker/FilePicker.tizen.cs, Xamarin.Essentials/FilePicker/FilePicker.uwp.cs, Xamarin.Essentials/FileSystem/FileSystem.android.cs, Xamarin.Essentials/FileSystem/FileSystem.ios.cs, Xamarin.Essentials/FileSystem/FileSystem.shared.cs, Xamarin.Essentials/Launcher/Launcher.tizen.cs, Xamarin.Essentials/MediaPicker/MediaPicker.android.cs, Xamarin.Essentials/PhoneDialer/PhoneDialer.android.cs, Xamarin.Essentials/Platform/Platform.android.cs, Xamarin.Essentials/Share/Share.android.cs, Xamarin.Essentials/Share/Share.shared.cs, Xamarin.Essentials/Sms/Sms.android.cs, Xamarin.Essentials/Types/FileProvider.android.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticator.android.cs
This PR solves a few issues.
* The URI to the picked file is **only valid as long as the calling Activity is alive**.  
Because we use an intermediate activity, this means that the URI almost immediately becomes invalid.  
To solve for this, we have to resolve the physical path of the picked file. Many providers have a way to retrieve the physical path, or the path is known based on the type of content URI.
* Some picked files **cannot be resolve to a physical path**.  
This might be because there are no permissions, or the file only exists as a stream from a file provider.  
In this case, we need to copy the file to a local location.
* Some picked **files are virtual*.   
This might be a Google docs spreadsheet which is not a real file format.
To solve this, we detect the virtual and …
=> Rework the "picker" results to correctly manage files

Xamarin.Essentials/Launcher/Launcher.macos.cs, Xamarin.Essentials/Map/Map.android.cs, Xamarin.Essentials/Map/Map.ios.watchos.macos.cs, Xamarin.Essentials/Map/Map.tizen.cs, Xamarin.Essentials/Map/Map.uwp.cs, Xamarin.Essentials/Types/PlacemarkExtensions.shared.cs
On Apple devices, if the placemark is invalid, then nothing happens. This is inconsistent with all the other platforms.
In this PR, I have launched the maps app according to the Apple guidelines and it seems to work. You will get the app and a message saying that the address could not be found. It will also allow for suggestions and a chance to edit. 
Tested on macOS and iOS. This does not apply to watchOS.
tvOS probably can use this method exclusively to support maps, but that is for another PR.
- Fixes #729
None.
On iOS and macOS, invalid addresses will open the maps app to the search page.
=> Launch the maps app when the placemark can't be found

Xamarin.Essentials/Platform/Platform.android.cs, Xamarin.Essentials/Share/Share.android.cs, Xamarin.Essentials/Types/FileProvider.android.cs
Currently, the share will use the `intent.PutParcelableArrayListExtra(Intent.ExtraStream, contentUris);` when the action is set to `Intent.ActionSend` which is an invalid combo.
=> Make sure to use the correct extra when sharing single files

DeviceTests/DeviceTests.Android/DeviceTests.Android.csproj, DeviceTests/DeviceTests.Android/MainActivity.cs, DeviceTests/DeviceTests.Android/TestInstrumentation.cs, DeviceTests/DeviceTests.Android/Tests/FileProvider_Tests.cs, DeviceTests/DeviceTests.Shared/AppActions_Tests.cs, DeviceTests/DeviceTests.Shared/Clipboard_Tests.cs, DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs, DeviceTests/DeviceTests.Shared/Flashlight_Tests.cs, DeviceTests/DeviceTests.Shared/Geocoding_Tests.cs, DeviceTests/DeviceTests.Shared/Permissions_Tests.cs, DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs, DeviceTests/DeviceTests.Shared/Traits.cs, DeviceTests/DeviceTests.iOS/AppDelegate.cs, DeviceTests/DeviceTests.iOS/DeviceTests.iOS.csproj, DeviceTests/DeviceTests.iOS/Main.cs, DeviceTests/DeviceTests.iOS/TestApplicationDelegate.cs, DeviceTests/build.cake, azure-pipelines.yml, nuget.config
* Generate the Android device test builds
* Switch to xharness
Added: 
Changed:
```csharp
}
```
=> Switch to xharness for much more stable CI tests

azure-pipelines.yml
Try run the tests for API 23, but if it fails, then ignore. We have other tests.
Added: 
Changed:
```csharp
}
```
=> Don't fail the build for API 23 as that is always failing on CI

Samples/Samples/ViewModel/FilePickerViewModel.cs, Xamarin.Essentials/FilePicker/FilePicker.ios.cs, Xamarin.Essentials/FileSystem/FileSystem.ios.cs, Xamarin.Essentials/MediaPicker/MediaPicker.ios.cs
This PR will make sure that when files are picked, they are read correctly. Typically, external apps can provide file using a file provider, so we need to make sure we use that file provider to read the file data.
This PR also fixes a memory leak. Previously, the file was picked and opened. This also had a limitation that once the stream is closed then it can never be opened. And, multiple opens will cause issues with the single stream.
- Fixes #1549
None.
When picking files from third party providers, request the data from the provider.
=> [iOS] Request the file data from file providers

Samples/Samples/ViewModel/TextToSpeechViewModel.cs, Xamarin.Essentials/TextToSpeech/TextToSpeech.ios.tvos.watchos.cs, Xamarin.Essentials/TextToSpeech/TextToSpeech.macos.cs
Use NSSynthesiser Attributes to correctly populate the X.E Locale properties on Mac.  
Fix Locale Name on iOS as it was incorrectly populating it with Language
Tweaked TTS demo, to list Languages, so that voices are changed correctly on all platforms.
- Fixes #1622 - Populate Mac Locale correctly
- Fixes #1624 - Make TTS demo behave consistently across platforms
None
Added: 
None
Changed:
[Mac] Pass each voice to the NSSpeechSynthesizer.AttributesForVoice(), so we can then popolate the Locale object correctly.
https://github.com/CartBlanche/Essentials/blob/dominique-FixTTSLocaleOnMac/Xamarin.Essentials/TextToSpeech/TextToSpeech.macos.cs#L15-L18
[iOS] Populate Name property correctly.
https://github.com/CartBlanche/Essentials/blob/dominique-FixTTSLocaleOnMac/Xamarin.Essentials/TextToSpeech/ …
=> Use NSSpeechSynthesizer.AttributesForVoice to correctly populate the X.E Locale on Mac. 

Xamarin.Essentials/Permissions/Permissions.ios.tvos.watchos.cs, Xamarin.Essentials/Types/LocationExtensions.ios.tvos.watchos.macos.cs
Make sure to actually use the correct method that was added in a previous fix. 
- Fixes #1589 
None.
None.
=> Make sure to actually use the correct method

Xamarin.Essentials/FilePicker/FilePicker.android.cs
If the permissions were denied, then throw.
- Fixes  #1649
None.
If the permissions are denied, then the picker does not launch.
=> Make sure to require permissions

Xamarin.Essentials/MediaPicker/MediaPicker.android.cs
Ensure the permissions are granted for the media picker
- Fixes #1656
=> Ensure granted

Xamarin.Essentials/WebAuthenticator/WebAuthenticatorIntermediateActivity.android.cs
Fix crash when using WebAuthenticator.AuthenticateAsync in latest version. While this might not be the best way to fix it, it fixes the issue (at least on our app). If a different fix is required, can this at least be given some priority? Thanks
No tests are added because I have no idea how I'd even write a test for this case
- Fixes #1586
None
None
=> Fix crash when using WebAuthenticator.AuthenticateAsync #1586

Xamarin.Essentials/SecureStorage/SecureStorage.ios.tvos.watchos.macos.cs, Xamarin.Essentials/SecureStorage/SecureStorage.shared.cs
Resolves secure storage access groups not working on iOS by ensuring that specified shared access groups are not overridden with a bundle-specific access group.
Implementation of changes discussed in thread below, removing bundle-specific override of access group for iOS:
https://github.com/xamarin/Essentials/pull/1351#discussion_r485128322
Changed:
- When access group is specified, SecureStorage explicitly uses shared access group provided.
- SecureStorage backwards compatibility if no access group supplied, ie. still uses old XaraminEssentials alias as documented
=> Fix Secure storage group not shareable between iOS applications

Xamarin.Essentials/DeviceDisplay/DeviceDisplay.ios.cs
- Related to issue #1729
Added: 
Changed:
```csharp
}
```
=> Fixes #1729 check for ios 13 on max frame rates

Xamarin.Essentials/Types/PlatformExtensions/ColorExtensions.ios.tvos.watchos.cs, Xamarin.Essentials/Types/PlatformExtensions/ColorExtensions.macos.cs
Better UIColor conversion uses rounding instead of cutting off decimals
fixes #1572
none
none
=> better UIColor conversion

Xamarin.Essentials/Contacts/Contacts.ios.macos.cs, Xamarin.Essentials/Email/Email.ios.cs, Xamarin.Essentials/FilePicker/FilePicker.ios.cs, Xamarin.Essentials/MediaPicker/MediaPicker.ios.cs, Xamarin.Essentials/Platform/Platform.ios.tvos.watchos.cs, Xamarin.Essentials/Sms/Sms.ios.cs
Using [`Rg.Plugins.Popup`](https://github.com/rotorgames/Rg.Plugins.Popup) and `Essentials` together, I noticed some problems:
- Closing Popups closes pickers and etc., but the tasks remain not finished.
- We don't have the option to specify a UIViewController before opening pickers
This is due not only to `Rg.Plugins.Popup`, but also to any projects that use custom controllers for rendering pages. 
Added: 
```csharp
public static partial class Platform
{
public static void Init(Func<UIViewController> getCurrentUIViewController)
}
```
- All tasks will be finished when the controller is closed
- Ability to change the parent controller for pickers
=> Improving the operation of PresentationControllers

docs/en/Xamarin.Essentials/FilePicker.xml
Help details were same as FilePicker.PickAsync
Added: 
Changed:
```csharp
}
```
=> Help details incorrect

Xamarin.Essentials/TextToSpeech/TextToSpeech.android.cs
There's a bug in Android TTS that if you cancel quickly after starting TTS, `SpeakAsync` will never return. This is because the `CancellationToken` was cancelled before the `TaskCompletionSource` was being assigned, so awaiting the `TaskCompletionSource` would wait forever. To fix, I moved the creation of the `TaskCompletionSource` before we register with the `CancellationToken`
- Fixes #1894
None
=> Fixes hang waiting for cancelled TextToSpeech

DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml, Samples/Samples.Android/Properties/AndroidManifest.xml, Xamarin.Essentials/FilePicker/FilePicker.android.cs, Xamarin.Essentials/MediaPicker/MediaPicker.android.cs
Due to changes in targeting Android 11 the read/write permissions are super blocked. We dont' need them though as the API doesn't require them
- Related to issue #1961
None.
No longer require permissions.
=> remove read/write storage permissions from filepicker/mediapicker on Android

Xamarin.Essentials/Permissions/Permissions.ios.tvos.watchos.cs
On IOS if you like to request LocationAlways you have to request locationWhenInUse first. This means in an average implementation one would have 2 consecutive calls
await Permissions.RequestAsync<Permissions.LocationWhenInUse>();  
await Permissions.RequestAsync<Permissions.LocationAlways>();  
Both use the static LocationManager instance.
Since RequestAsync<Permissions.LocationWhenInUse>() sets the result of the task completition source before cleaning up its locationManager there is a race condition where RequestAsync<Permission.LocationAlways>() already runs and thus this cleanup disposes the locationManager used by the second call. This will not always be the case but in my test around 50% of the time. Workaround wait 3-10 seconds in between the calls
- Related to issue #1489 
Provide …
=> set result after cleanup of locationmanager #1489

Xamarin.Essentials/PhoneDialer/PhoneDialer.ios.cs
Doesn't swallow the exception because of the `async void` that was going on
- Fixes #1652
- Fixes #1984
N/A
Doesn't swallow the exception because of the `async void` that was going on
=> Surface exception for not supported phone number on iOS PhoneDialer

Xamarin.Essentials/Geolocation/Geolocation.android.cs, Xamarin.Essentials/Permissions/Permissions.shared.cs
Allow restricted permissions for "gatekeepers" on android geolocation methods
(https://github.com/xamarin/Essentials/issues/1972)
Optional parameter added to Permissions.EnsureGrantedAsync that also allows restricted to pass internal gatekeepers.  Default is set to false, so only methods where this is required functionality will care
=> Fix #1972 - allow restricted permissions for geolocation on android

DeviceTests/DeviceTests.Shared/VersionTracking_Tests.cs, Xamarin.Essentials/VersionTracking/VersionTracking.shared.cs
Version downgrades (e.g. from "1.1.0" to "1.0.1") are possible on certain platforms (e.g. on iOS with TestFlight) and thus should be handled correctly by VersionTracking module - especially if the version was already installed previously.
Since this is a bugfix (not a feature) covered by unit tests no samples are provided (see PR checklist).
- Related to issue #1960 
None
Observable behavior/semantics of the following API elements can change but **only in downgrade scenarios** described above:
- ``VersionTracking.IsFirstLaunchForCurrentVersion``
- ``VersionTracking.IsFirstLaunchForCurrentBuild``
- ``VersionTracking.PreviousVersion``
- ``VersionTracking.PreviousBuild``
- ``VersionTracking.FirstInstalledVersion``
- ``VersionTracking.FirstInstalledBuild``
- ``VersionTracking.VersionHistory`` …
=> Correctly handle version downgrades (e.g. via TestFlight)

Xamarin.Essentials/AppInfo/AppInfo.ios.tvos.watchos.macos.cs
Adding suppression for obsolete for the time being. We need to fix this properly later on, but this will fix the builds for now.
=> Add suppression for iOS FromBundleIdentifier obsolete

Xamarin.Essentials/WebAuthenticator/WebAuthenticator.android.cs
This will allow the system browser to be used instead of failing completely if Chrome Custom tabs are not available or cannot be used for any reason.
=> Android WebAuthenticator fallback to system browser if Chrome Custom tabs are not available

docs/en/Xamarin.Essentials/PointExtensions.xml
Typo "point ot"→"point to"
https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.pointextensions.tosystempointf?view=xamarin-essentials-android
https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/PointExtensions.xml
#PingMSFTDocs
Added: 
Changed:
```csharp
public static void SomeMethod(string …
```
=> Typo "point ot"→"point to"

Samples/Sample.Server.WebAuthenticator/Sample.Server.WebAuthenticator.csproj
Bump AspNet.Security.OAuth.Apple to 3.1.8 to resolve https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/security/advisories/GHSA-3893-h8qg-6h5f.
I've also submitted a similar patch to https://github.com/dotnet/maui/pull/9855.
=> Bump AspNet.Security.OAuth.Apple to 3.1.8

PRODUCT-FEEDBACK.md, README.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
**DO NOT MERGE THIS PULL REQUEST WHILE IN DRAFT STATUS!** Some of the changes to links and other content are not valid until after go-live.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: …
=> [BULK UPDATE] DocuTune - Rebranding links

Xamarin.Essentials/AppInfo/AppInfo.android.cs, Xamarin.Essentials/Email/Email.android.cs, Xamarin.Essentials/Launcher/Launcher.android.cs, Xamarin.Essentials/Map/Map.android.cs, Xamarin.Essentials/PhoneDialer/PhoneDialer.android.cs, Xamarin.Essentials/Sms/Sms.android.cs
We shouldn't do this. Browser has an option
- Related to issue #2023
=> Remove launch adjacent Fixes #2023

Xamarin.Essentials/MediaPicker/MediaPicker.android.cs, Xamarin.Essentials/SecureStorage/SecureStorage.android.cs
Thanks to @Ghostbird in https://github.com/dotnet/maui/pull/12766
Fix the MediaPicker that is requesting permissions that are not correct for Android 33.
- Fixes #2037
- Potentially #2041
None.
Skips the check for `StorageWrite` because that permission is not needed and probably not needed in many versions...
=> Fix MediaPicker capture methods in Android 13+

Xamarin.Essentials/Share/Share.ios.cs
See: https://github.com/dotnet/maui/pull/13708
=> fix share title on iOS

Xamarin.Essentials/WebAuthenticator/WebAuthenticator.android.cs, Xamarin.Essentials/WebAuthenticator/WebAuthenticatorCallbackActivity.android.cs, azure-pipelines.yml
* Maybe fixes #2070
* Maybe fixes #2081
=> Fix failing auth redirect on Android

Xamarin.Essentials/Connectivity/Connectivity.android.cs
=> Remove wrong Connectivity dispose calls on Android

Xamarin.Essentials/FilePicker/FilePicker.uwp.cs
When using FilePicker on UWP it will add the entries to something that is called the FutureAccessList. However, that list has a maximum amount of entries and when it reaches that, it will break. This change will add some more robustness.
This adds:
* Check if we're going over the limit with the picked files
* If yes; clean up the list starting with the oldest entries (assumed)
* Add the last _n_ number of picked files back to the list, where _n_ is the amount of files picked, or if that exceed the maximum of the FutureAccessList, it will take that maximum.
* Wraps this whole process in a try/catch so we don't break users apps when something goes wrong, its not that important.
- Fixes #2061
- Closes #2068
Describe any non-bug related behavioral changes that may change how users app behaves …
=> Make UWP FilePicker FutureAccessList more robust

DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml, Xamarin.Essentials/Battery/Battery.android.cs, Xamarin.Essentials/Connectivity/Connectivity.android.cs, Xamarin.Essentials/Platform/Platform.android.cs
Ports over https://github.com/dotnet/maui/pull/18520/ to Xamarin.Essentials
- Fixes #2107
=> Add API 34/Android 14 compatibility for Connectivity & Battery

Samples/Sample.Server.WebAuthenticator/Sample.Server.WebAuthenticator.csproj
In order to update the dependencies and remove vulnerabilities
=> Update WebAuthenticator Sample app dependencies

docs/en/Xamarin.Essentials/WebAuthenticator.xml
AuthenticateAsync throws a TaskCanceledException if the user aborts the process. This should be included in the documentation
Added documentation for the exception thrown when users cancel the process.
None - documentation fix only.
None - documentation fix only.
None - documentation fix only.
=> Update WebAuthenticator.xml to document exception types
